# -*- coding: utf-8 -*-
"""Dados da campanha "A Garagem do Vo" (modo robos). Modulo PURO: so dados, sem pygame e sem imports.

Regras de escrita (verificadas por tests/test_story.py): tudo em Latin-1; so aspas retas (") e tres
pontos ASCII ("..."); fala <= 260 chars e cabe em <= 4 linhas de 780 px (pygame Font(None, 28));
opcao de escolha <= 46 chars; nome de exibicao <= 14 chars; flags ASCII <= 32 chars (<= 48 no total).
Ids de cena/personagem/time/torneio sao ESTAVEIS (vao para o save): mudar um id existente exige migracao.

Como ler (resumo dos campos)
----------------------------
CHARACTERS[id] = {"name": exibicao em maiusculas (<=14), "color": RGB do nome/caixa,
    "skin": RGB, "hair": (estilo, RGB), "acc": [acessorios], "outfit": (tipo, RGB)}.
    Estilos/acessorios/roupas validos: HAIR_STYLES, ACCESSORIES, OUTFITS (o passo 9 desenha por codigo).
MOODS: expressoes validas (o retrato troca olhos/boca/suor conforme o humor).
BGS: ids de cenario (o desenho e do passo 9).
TEAMS[id] = {"name" (<=24), "color", "ovr", "names" (5 robos <=12, unicos), "chassis" (5, em
    robots.CHASSIS), "paint" (RGB dos robos), "perfect" (True = sem jitter nos atributos)}.
    Ordem dos 5 slots = garage.LINEUP_SLOTS (GK, DEF, MID, MID, ATT).
SCENES[id] = {"bg", "cast": [ids], "lines": [...]}. Item de "lines":
    (who, mood, text)  |  (who, mood, text, cond)  |  {"q", "opts": [{"t", "fx", "reply": [linhas]}]}
    who = id de personagem; cond = ("flag", nome) | ("noflag", nome) | ("done", scene_id).
    fx (so estas chaves): flag (str), scrap (int, <=100), xp_hero (int), xp_team (int),
    piece ({"model": parts.PARTS, "rar": 0..3}). Escolha: opcoes 2-3; "fx" e "reply" opcionais.
TOURNAMENTS[id]: ver o bloco proprio (formato, hooks, boss_delta/regular_delta).
CHAPTERS: lista ordenada; "nodes" em ordem: ("scene", id) | ("tournament", id) | ("chapter_end", cap_id)
    | ("end", scene_id)  [o ultimo capitulo da campanha termina com ("end", cena de epilogo)].
    "draft": True = esqueleto (nodes vazio) que o teste de alcancabilidade ignora.
REWARDS[id]: aplicado UMA vez ao fechar o capitulo (chave "reward:<id>" em `done`): scrap, piece,
    recruits [{"name","role","chassis","base_ovr","level","paint","piece"?}], unlock [chassis],
    xp_hero, xp_team, equip_hero_piece ({"model","rar"} ou None).
"""

STORY_VERSION = 1

# --- pity (derrotas seguidas no chefe) ---------------------------------------------------------
PITY_STEP = 1      # -1 de Forca do chefe por derrota seguida
PITY_MAX = 3       # ate -3; zera ao vencer

# --- personagens --------------------------------------------------------------------------------
HAIR_STYLES = ("espetado", "calvo", "longo", "curto", "ondulado", "raspado", "none")
ACCESSORIES = ("oculos_redondos", "oculos_testa", "oculos_grandes", "headset", "bandana", "bigode",
               "luvas", "canetas", "graxa", "chinelo", "fita", "capacete", "apito", "kimono")
OUTFITS = ("moletom", "blazer", "jaleco", "terno", "uniforme", "camiseta", "kimono", "robo")

CHARACTERS = {
    "teo": {"name": "TÉO", "color": (255, 90, 80), "skin": (240, 200, 160),
            "hair": ("espetado", (60, 40, 30)), "acc": [], "outfit": ("moletom", (220, 50, 50))},
    "ambrosio": {"name": "PROF. AMBRÓSIO", "color": (180, 190, 210), "skin": (235, 195, 160),
                 "hair": ("calvo", (170, 170, 175)), "acc": ["oculos_redondos", "bigode", "canetas"],
                 "outfit": ("jaleco", (230, 230, 235))},
    "vivi": {"name": "VIVI", "color": (80, 130, 255), "skin": (245, 215, 190),
             "hair": ("longo", (20, 30, 80)), "acc": [], "outfit": ("blazer", (245, 245, 250))},
    "bia": {"name": "BIA", "color": (255, 160, 40), "skin": (200, 150, 110),
            "hair": ("curto", (40, 25, 20)), "acc": ["bandana", "oculos_testa", "graxa"],
            "outfit": ("camiseta", (90, 90, 100))},
    "dudu": {"name": "DUDU", "color": (80, 230, 120), "skin": (225, 180, 140),
             "hair": ("ondulado", (30, 30, 30)), "acc": ["headset", "oculos_grandes"],
             "outfit": ("moletom", (40, 170, 90))},
    "augusto": {"name": "DR. AUGUSTO", "color": (200, 240, 255), "skin": (245, 220, 200),
                "hair": ("curto", (200, 205, 215)), "acc": ["luvas"], "outfit": ("terno", (250, 250, 255))},
    "gervasio": {"name": "DIR. GERVÁSIO", "color": (200, 170, 120), "skin": (235, 190, 150),
                 "hair": ("raspado", (90, 70, 50)), "acc": ["bigode"], "outfit": ("terno", (90, 80, 70))},
    "rodolfo": {"name": "CAP. RODOLFO", "color": (150, 160, 170), "skin": (215, 170, 135),
                "hair": ("raspado", (50, 50, 55)), "acc": [], "outfit": ("uniforme", (60, 70, 80))},
    "helena": {"name": "DRA. HELENA", "color": (190, 130, 255), "skin": (225, 185, 150),
               "hair": ("curto", (70, 50, 90)), "acc": ["oculos_redondos"],
               "outfit": ("blazer", (80, 60, 120))},
    "kenji": {"name": "KENJI", "color": (255, 120, 160), "skin": (240, 205, 170),
              "hair": ("espetado", (20, 20, 25)), "acc": ["bandana"], "outfit": ("kimono", (240, 240, 240))},
    "narrador": {"name": "NARRADOR", "color": (150, 170, 200), "skin": (200, 200, 200),
                 "hair": ("none", (0, 0, 0)), "acc": [], "outfit": ("camiseta", (60, 70, 100))},
    "ze": {"name": "ZÉ POEIRA", "color": (0, 200, 220), "skin": (170, 180, 190),
           "hair": ("none", (0, 0, 0)), "acc": ["chinelo", "fita"], "outfit": ("robo", (120, 130, 140))},
}

MOODS = ("neutro", "feliz", "susto", "triste", "bravo", "pensando", "convencida", "convencido",
         "corada", "suor", "espirro", "calmo", "cansado", "robo")

BGS = ("garagem", "oficina", "escola", "cantina", "quadra", "ginasio", "arena", "camarim",
       "federacao", "estadio", "mundial")

# --- times --------------------------------------------------------------------------------------
_CH = ["Goleiro", "Tanque", "Disco", "Disco", "Velocista"]

TEAMS = {
    "xadrez": {"name": "Clube do Xadrez", "color": (120, 120, 150), "ovr": 36,
               "names": ["Torre", "Bispo", "Cavalo", "Peão", "Rainha"], "chassis": list(_CH),
               "paint": (225, 225, 235), "perfect": False},
    "turma3b": {"name": "Turma 3ºB", "color": (240, 190, 60), "ovr": 38,
                "names": ["Zeca", "Maju", "Tato", "Pri", "Gui"], "chassis": list(_CH),
                "paint": (250, 200, 80), "perfect": False},
    "fundao": {"name": "Fundão FC", "color": (150, 110, 70), "ovr": 39,
               "names": ["Soneca", "Cochilo", "Bocejo", "Preguiça", "Ronco"], "chassis": list(_CH),
               "paint": (160, 120, 80), "perfect": False},
    "gremio": {"name": "Grêmio", "color": (60, 160, 100), "ovr": 40,
               "names": ["Ata", "Pauta", "Voto", "Moção", "Estatuto"], "chassis": list(_CH),
               "paint": (70, 170, 110), "perfect": False},
    "teatro": {"name": "Clube de Teatro", "color": (210, 70, 130), "ovr": 42,
               "names": ["Hamlet", "Julieta", "Cena", "Bis", "Ensaio"], "chassis": list(_CH),
               "paint": (220, 90, 150), "perfect": False},
    # Robos da Limpex-patrocinada de Vivi: perfeitos (sem jitter), brancos com marca ciano
    "impecaveis": {"name": "Os Impecáveis", "color": (0, 220, 255), "ovr": 46,
                   "names": ["LX-01", "LX-02", "LX-03", "LX-04", "LX-05"], "chassis": list(_CH),
                   "paint": (235, 248, 255), "perfect": True},
    # ---- Cap. 2 (Taca Vale do Po)
    "padaria": {"name": "Padaria Pão Quente", "color": (230, 180, 90), "ovr": 43,
                "names": ["Baguete", "Brioche", "Sonho", "Rosca", "Broa"],
                "chassis": ["Goleiro", "Tanque", "Disco", "Disco", "Velocista"],
                "paint": (235, 195, 120), "perfect": False},
    "churrasco": {"name": "Tios do Churrasco", "color": (210, 80, 50), "ovr": 43,
                  "names": ["Picanha", "Espeto", "Brasa", "Farofa", "Costela"],
                  "chassis": ["Tanque", "Tanque", "Disco", "Disco", "Velocista"],
                  "paint": (200, 85, 55), "perfect": False},
    "academia": {"name": "Academia Sem Esforço", "color": (90, 190, 200), "ovr": 45,
                 "names": ["Halter", "Supino", "Whey", "Barra", "Esteira"],
                 "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                 "paint": (110, 200, 205), "perfect": False},
    # revanche da Vivi: robos perfeitos, brancos com marca ciano (numeracao propria)
    "impec2": {"name": "Impecáveis Mk II", "color": (0, 220, 255), "ovr": 46,
               "names": ["LX-06", "LX-07", "LX-08", "LX-09", "LX-10"],
               "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
               "paint": (235, 248, 255), "perfect": True},
    "faxina": {"name": "Esquadrão Faxina", "color": (130, 150, 140), "ovr": 50,
               "names": ["Rodo", "Vassoura", "Esfregão", "Balde", "Flanela"],
               "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
               "paint": (120, 140, 130), "perfect": False},
    # ---- Cap. 3 (Estadual Limpex Cup)
    "bombeiros": {"name": "Bombeiros Voluntários", "color": (230, 60, 50), "ovr": 46,
                  "names": ["Mangueira", "Sirene", "Hidrante", "Machado", "Escada"],
                  "chassis": ["Goleiro", "Tanque", "Tanque", "Disco", "Velocista"],
                  "paint": (225, 55, 50), "perfect": False},
    "coral": {"name": "Coral Desafinado", "color": (170, 110, 220), "ovr": 48,
              "names": ["Soprano", "Tenor", "Baixo", "Contralto", "Maestro"],
              "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
              "paint": (170, 110, 220), "perfect": False},
    "detetives": {"name": "Detetives do Quarteirão", "color": (140, 110, 80), "ovr": 48,
                  "names": ["Lupa", "Pista", "Álibi", "Digital", "Mistério"],
                  "chassis": ["Goleiro", "Disco", "Disco", "Orbital", "Velocista"],
                  "paint": (150, 120, 85), "perfect": False},
    "sindicato": {"name": "Sindicato dos Zeladores", "color": (90, 120, 160), "ovr": 51,
                  "names": ["Chaveiro", "Zelador", "Porteiro", "Síndico", "Manobra"],
                  "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                  "paint": (100, 130, 170), "perfect": False},
    # chefe do Cap. 3: serie L-9 (perfeitos, brancos com ciano)
    "imaculados": {"name": "Imaculados L-9", "color": (0, 230, 255), "ovr": 54,
                   "names": ["LX9-01", "LX9-02", "LX9-03", "LX9-04", "LX9-05"],
                   "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                   "paint": (245, 252, 255), "perfect": True},
    # ---- Cap. 4 (Copa Brasil)
    "escoteiros": {"name": "Escoteiros Eletrônicos", "color": (90, 160, 80), "ovr": 50,
                   "names": ["Nó", "Bússola", "Lanterna", "Barraca", "Mapa"],
                   "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                   "paint": (100, 170, 90), "perfect": False},
    "cartorio": {"name": "Cartório Veloz", "color": (170, 150, 110), "ovr": 50,
                 "names": ["Selo", "Firma", "Carimbo", "Protocolo", "Fila"],
                 "chassis": ["Goleiro", "Tanque", "Tanque", "Orbital", "Velocista"],
                 "paint": (180, 160, 120), "perfect": False},
    "taxistas": {"name": "Cooperativa dos Taxistas", "color": (240, 200, 40), "ovr": 51,
                 "names": ["Bandeira", "Buzina", "Rota", "Corrida", "Troco"],
                 "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                 "paint": (245, 205, 50), "perfect": False},
    "reserva": {"name": "Platinum Reserva", "color": (190, 200, 215), "ovr": 53,
                "names": ["PR-01", "PR-02", "PR-03", "PR-04", "PR-05"],
                "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                "paint": (225, 232, 245), "perfect": True},
    "platinum": {"name": "Divisão Platinum", "color": (210, 225, 245), "ovr": 56,
                 "names": ["PT-01", "PT-02", "PT-03", "PT-04", "PT-05"],
                 "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                 "paint": (240, 245, 255), "perfect": True},
    # ---- Cap. 5 (Mundial de Aspiradores)
    "sakura": {"name": "Sakura Vacuum Club", "color": (255, 170, 190), "ovr": 55,
               "names": ["Mochi", "Hana", "Neko", "Ramen", "Origami"],
               "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
               "paint": (255, 175, 195), "perfect": False},
    "staub": {"name": "Staubsauger Sporting", "color": (200, 170, 60), "ovr": 57,
              "names": ["Wurst", "Brezel", "Kuckuck", "Pünktlich", "Zeppelin"],
              "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
              "paint": (210, 180, 70), "perfect": False},
    "aspirateurs": {"name": "Les Aspirateurs", "color": (90, 120, 220), "ovr": 57,
                    "names": ["Baguette", "Croissant", "Brie", "Béret", "Moustache"],
                    "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                    "paint": (100, 130, 225), "perfect": False},
    "dustbunnies": {"name": "Dust Bunnies USA", "color": (230, 90, 90), "ovr": 58,
                    "names": ["Tex", "Donut", "Cowboy", "Popcorn", "Jumbo"],
                    "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                    "paint": (235, 100, 100), "perfect": False},
    "kenji_team": {"name": "Dojo do Kenji", "color": (255, 120, 160), "ovr": 59,
                   "names": ["Katana", "Bonsai", "Tofu", "Samurai", "Haiku"],
                   "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
                   "paint": (245, 245, 250), "perfect": False},
    # chefe final: Hiperlimpos X-9 de Augusto (perfeitos, SEM attr_override)
    "x9": {"name": "Hiperlimpos X-9", "color": (0, 240, 255), "ovr": 63,
           "names": ["X9-01", "X9-02", "X9-03", "X9-04", "X9-05"],
           "chassis": ["Goleiro", "Tanque", "Disco", "Orbital", "Velocista"],
           "paint": (250, 255, 255), "perfect": True},
}

# --- torneios -----------------------------------------------------------------------------------
# format "single": 1 partida (treino; resultado nao bloqueia). format "cup": grupo de 4 (jogador + 3
#   adversarios "group", 3 jogos, top 2 avanca) + semifinal "sf" + final "final" (+ quartas "qf" no
#   Mundial). O chefe ("boss") e sempre o adversario da final. Estagios: G1 G2 G3 [QF] SF F.
# Calibragem (ver PLANO): Forca esperada do jogador F (CHAPTERS F_start>F_end). ovr do chefe =
#   F_end - boss_delta (chefe final: 0, demais: +1); regulares ficam ~regular_delta=(5..7) abaixo
#   de F_start; a semifinal e "forte" (~+4 abaixo). Eliminacao no grupo reinicia o torneio com
#   semente nova; derrota na SF/F so repete aquela partida (pity no chefe).
# hooks: cenas amarradas ao torneio (jogadas uma vez, controladas por `done`):
#   "before": {estagio: cena} antes da partida; "after": {estagio: cena} apos VENCER o estagio;
#   "win": cena ao vencer a final; "lose": cena apos perder SF/final; "elim": cena apos eliminacao
#   no grupo (o torneio recomeca em seguida).
TOURNAMENTS = {
    "t_p_treino": {
        "chapter": "P", "local": "Quadra do Colégio Santa Faísca", "bg": "quadra", "format": "single",
        "group": [], "qf": None, "sf": None, "final": "xadrez", "boss": "xadrez",
        "boss_delta": 8, "regular_delta": (8, 8),
        "hooks": {"before": {}, "after": {}, "win": None, "lose": None, "elim": None},
    },
    "t_c1": {
        "chapter": "1", "local": "Quadra do Colégio Santa Faísca", "bg": "quadra", "format": "cup",
        "group": ["turma3b", "fundao", "gremio"], "qf": None, "sf": "teatro", "final": "impecaveis",
        "boss": "impecaveis", "boss_delta": 1, "regular_delta": (5, 7),
        "hooks": {"before": {"G2": "c1_g2_fundao_pre", "F": "c1_final_pre"},
                  "after": {"SF": "c1_sf_pos"},
                  "win": "c1_final_win", "lose": "c1_final_lose", "elim": "c1_repescagem"},
    },
    "t_c2": {
        "chapter": "2", "local": "Ginásio Municipal", "bg": "ginasio", "format": "cup",
        "group": ["padaria", "churrasco", "academia"], "qf": None, "sf": "impec2", "final": "faxina",
        "boss": "faxina", "boss_delta": 1, "regular_delta": (5, 7),
        "hooks": {"before": {"G2": "c2_g_gag", "SF": "c2_sf_vivi_pre", "F": "c2_final_pre"},
                  "after": {"SF": "c2_sf_vivi_pos"},
                  "win": "c2_final_win", "lose": "c2_final_lose", "elim": "c2_repescagem"},
    },
    # Cap. 3: c3_logs e jogada apos o grupo (after G3) e c3_sf_pos apos a semifinal (cada estagio so
    # tem uma cena "after"; c3_final_pre fica no before F).
    "t_c3": {
        "chapter": "3", "local": "Arena Estadual", "bg": "arena", "format": "cup",
        "group": ["bombeiros", "coral", "detetives"], "qf": None, "sf": "sindicato", "final": "imaculados",
        "boss": "imaculados", "boss_delta": 1, "regular_delta": (5, 7),
        "hooks": {"before": {"G2": "c3_g_gag", "F": "c3_final_pre"},
                  "after": {"G3": "c3_logs", "SF": "c3_sf_pos"},
                  "win": "c3_final_win", "lose": "c3_final_lose", "elim": "c3_repescagem"},
    },
    # Cap. 4: c4_vivi_break apos o grupo (after G3); Vistoria antes do G2.
    "t_c4": {
        "chapter": "4", "local": "Estádio Nacional", "bg": "estadio", "format": "cup",
        "group": ["escoteiros", "cartorio", "taxistas"], "qf": None, "sf": "reserva", "final": "platinum",
        "boss": "platinum", "boss_delta": 1, "regular_delta": (5, 7),
        "hooks": {"before": {"G2": "c4_g_vistoria", "SF": "c4_sf_pre", "F": "c4_final_pre"},
                  "after": {"G3": "c4_vivi_break", "SF": "c4_sf_pos"},
                  "win": "c4_final_win", "lose": "c4_final_lose", "elim": "c4_repescagem"},
    },
    # Cap. 5: grupo + quartas (QF) + SF + final = 6 partidas. A final e do X-9 de Augusto (boss_delta
    # negativo: o chefe final fica ~0,5 acima da Forca esperada de fim de capitulo).
    "t_c5": {
        "chapter": "5", "local": "Arena Global de Neo-Tóquio", "bg": "mundial", "format": "cup",
        "group": ["sakura", "staub", "aspirateurs"], "qf": "dustbunnies", "sf": "kenji_team", "final": "x9",
        "boss": "x9", "boss_delta": -0.5, "regular_delta": (4, 7),
        "hooks": {"before": {"G1": "c5_g1_gag", "G2": "c5_g2_gag", "G3": "c5_g3_gag", "QF": "c5_qf_pre",
                             "SF": "c5_sf_kenji", "F": "c5_final_pre"},
                  "after": {"QF": "c5_qf_pos"},
                  "win": "c5_final_win", "lose": "c5_final_lose", "elim": "c5_repescagem"},
    },
}

# --- cenas --------------------------------------------------------------------------------------
SCENES = {
    # ------------------------------------------------------------------ Prologo
    "p1_garagem": {"bg": "garagem", "cast": ["teo", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Sábado, 14h. Garagem do Vô Nestor. Cheiro de graxa, naftalina e pão de queijo de 1998."),
        ("teo", "cansado", "Vô, o senhor disse que tinha um tesouro aqui. Isso é um aspirador de pó. Com fita crepe. E um chinelo preso."),
        ("ze", "robo", "Bzzzt... cof, cof... (a rodinha esquerda cai e rola até a porta)"),
        ("teo", "susto", "Ele perdeu uma roda sozinho! Eu nem encostei!"),
        ("ambrosio", "feliz", "Esse é o Aspiradex Turbo 74, rapaz. Aposentou três campeões regionais antes de você nascer."),
        ("teo", "susto", "O senhor estava aí atrás desde quando?!"),
        ("ambrosio", "neutro", "Desde as 13h. Seu avô pediu pra eu vigiar a garagem e eu cochilei. Ambrósio Pimenta, professor de robótica do Colégio Santa Faísca. Prazer."),
        ("ambrosio", "neutro", "O clube de robótica vai fechar se não ganhar a Copa Interclasses. Faltam quatro robôs e um milagre. Você tem um robô. E um chinelo."),
        ("teo", "pensando", "O chinelo é estrutural."),
        {"q": "O que o Téo responde?", "opts": [
            {"t": "Vamos consertar o Zé Poeira hoje!", "fx": {"xp_hero": 20},
             "reply": [("ambrosio", "feliz", "Gostei da energia! Pega a chave de fenda e o pão de queijo.")]},
            {"t": "Eu vendo ele no ferro-velho e vou pra casa.", "fx": {"scrap": 25},
             "reply": [("ambrosio", "suor", "Cabeça fria. Mas olha como o Zé Poeira está olhando pra você."),
                       ("ze", "robo", "Bip."),
                       ("teo", "triste", "Tá. Eu conserto. Mas só porque ele fez bip.")]},
        ]},
    ]},

    "p2_oficina": {"bg": "oficina", "cast": ["teo", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Domingo, 9h. A oficina do Colégio Santa Faísca. Doze bancadas, onze com poeira e uma com um bolo."),
        ("ambrosio", "feliz", "Bem-vindo à Oficina. Regra um: robô precisa de peças. Regra dois: peça se compra com sucata. Regra três: o bolo é da Dona Odete, não encoste."),
        ("teo", "neutro", "Professor, eu só trouxe o Zé Poeira. E o chinelo."),
        ("ambrosio", "pensando", "Hum. Deixa eu olhar a caixa de achados e perdidos... (três canetas caem do bolso dele)"),
        ("ambrosio", "feliz", "Achei! Um motor, uma bateria e uma escova de sucção. Tudo meio usado, mas funciona. Quase."),
        ("teo", "susto", "\"Quase\" é a palavra mais assustadora de uma oficina."),
        ("ambrosio", "neutro", "Cada peça entra num encaixe. Motor deixa rápido, bateria deixa durar, escova ajuda a dominar a bola. É só equipar na aba Bancada."),
        ("ze", "robo", "Bip. (a escova de sucção liga sozinha e puxa uma meia do chão)"),
        ("teo", "feliz", "Ele gostou! Olha, ele já achou uma meia!"),
        ("ambrosio", "cansado", "Essa meia é minha. Está desaparecida desde 2019. Mas tudo bem."),
        ("narrador", "neutro", "Três peças instaladas depois, o Zé Poeira anda em linha reta. Quase."),
        {"q": "O que o Téo faz com o chinelo?", "opts": [
            {"t": "Deixa. O chinelo é estrutural.", "fx": {"flag": "chinelo_fica", "xp_hero": 10},
             "reply": [("ambrosio", "feliz", "Respeito. Ninguém discute com um chinelo convicto.")]},
            {"t": "Troca o chinelo por um parafuso.", "fx": {"scrap": 20},
             "reply": [("ze", "robo", "Bzzzt. (a rodinha cai de novo, de ofendida)"),
                       ("teo", "suor", "Tá bom, tá bom. Acho que o parafuso precisa de mais tempo.")]},
        ]},
    ]},

    "p3_peneira_pre": {"bg": "quadra", "cast": ["teo", "ambrosio", "gervasio", "ze"], "lines": [
        ("narrador", "neutro", "Segunda-feira, 15h. Quadra do Santa Faísca. A peneira vale uma vaga na Interclasses. O adversário é o Clube do Xadrez."),
        ("gervasio", "neutro", "Atenção, atenção. Hoje o colégio decide se o clube de robótica merece o orçamento anual de... (olha a prancheta) ...dois reais e cinquenta."),
        ("teo", "susto", "Dois e cinquenta?!"),
        ("gervasio", "pensando", "Mais um clipe, se pedirem com educação. Os clipes são caros, Sr. Moreira."),
        ("ambrosio", "suor", "Diretor Gervásio, o clube tem história! Em 1998..."),
        ("gervasio", "neutro", "Em 1998 eu era estagiário e perdi o almoço numa demonstração. Não tenho boas memórias."),
        ("teo", "neutro", "Quem a gente enfrenta hoje, professor?"),
        ("ambrosio", "pensando", "O Clube do Xadrez. Eles pensam oito jogadas à frente. Os robôs andam duas."),
        ("teo", "feliz", "Então a gente chuta antes de eles terminarem de pensar!"),
        ("ambrosio", "feliz", "Esse é o espírito. Aperte o botão, Téo. E reze pela rodinha."),
        ("ze", "robo", "Bzzzt. Bip. (a rodinha esquerda gira, firme. Por enquanto.)"),
    ]},

    "p4_peneira_pos": {"bg": "quadra", "cast": ["teo", "ambrosio", "gervasio", "ze"], "lines": [
        ("narrador", "neutro", "Fim da peneira. O placar já está no quadro. O sorriso do Téo independe dele."),
        ("gervasio", "neutro", "Sr. Moreira, vi o que precisava ver. O robô cai, o chinelo balança, e mesmo assim ele não desiste."),
        ("teo", "feliz", "Isso é um elogio?"),
        ("gervasio", "pensando", "É uma observação administrativa. O clube fica. Por enquanto."),
        ("ambrosio", "feliz", "Por enquanto! Ouviu, Téo? Por enquanto!"),
        ("gervasio", "neutro", "Em três semanas começa a Copa Interclasses. Se o clube não ganhar, fecha. A sala vira depósito de caixas de giz."),
        ("teo", "susto", "Ganhar?! Contra o colégio inteiro?!"),
        ("ambrosio", "neutro", "Contra as turmas, o Grêmio e os Impecáveis. Um bom pessoal, todos com patrocínio e nenhum com chinelo."),
        ("teo", "pensando", "Professor, quantas vezes o clube já ganhou a Interclasses?"),
        ("ambrosio", "suor", "Hm. Eu cochilei durante essa parte da história."),
        ("teo", "feliz", "Então a gente escreve a parte nova. Zé Poeira, bora?"),
        ("ze", "robo", "Bip. (a rodinha cai. Todos fingem que não viram.)"),
    ]},

    # ------------------------------------------------------------------ Cap. 1
    "c1_intro": {"bg": "quadra", "cast": ["teo", "ambrosio", "gervasio", "bia"], "lines": [
        ("narrador", "neutro", "Copa Interclasses, dia do sorteio. A urna é uma caixa de sapato com a etiqueta \"NÃO ABRIR\"."),
        ("gervasio", "neutro", "Grupo B: Turma 3ºB, Fundão FC, Grêmio e o clube de robótica. Se alguém lembrar de aplaudir, aplauda."),
        ("teo", "feliz", "Três jogos no grupo, e os dois primeiros passam! (aplaude sozinho)"),
        ("ambrosio", "pensando", "O Grêmio... Cuidado. Eles têm patrocínio. E um aspirador em cada gaveta."),
        ("teo", "neutro", "Professor, quem é aquela de bandana, colocando fita num robô alheio?"),
        ("bia", "neutro", "Esse aqui estava solto. Prendi com fita. Agora está firme. De nada."),
        ("ambrosio", "feliz", "Bia Gambiarra, a melhor mecânica do colégio! Bia, que tal entrar no clube?"),
        ("bia", "bravo", "Entrar no clube de robótica? Gambiarra não é esporte, Professor. É um estilo de vida."),
        ("teo", "feliz", "A gente tem fita crepe e um chinelo!"),
        ("bia", "pensando", "...Um chinelo estrutural?"),
        ("teo", "feliz", "Estrutural!"),
        ("bia", "corada", "Vou pensar. Não conta pra ninguém que eu pensei."),
        {"q": "O que o Téo diz pra Bia?", "opts": [
            {"t": "Você faz parte do time, Bia!", "fx": {"flag": "bia_convidada", "xp_team": 10},
             "reply": [("bia", "neutro", "Pressão emocional. Eficiente, mas não vou admitir.")]},
            {"t": "Sem pressão. A porta fica aberta.", "fx": {"flag": "bia_livre", "scrap": 15},
             "reply": [("bia", "feliz", "Gente educada é perigosa. Toma, achei isso no chão. Era seu mesmo.")]},
        ]},
    ]},

    "c1_g2_fundao_pre": {"bg": "quadra", "cast": ["teo", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Segundo jogo do grupo. Fundão FC, o time do fundo da sala. Eles chegam atrasados e bocejando."),
        ("teo", "neutro", "Professor, os robôs deles estão parados no meio do campo."),
        ("ambrosio", "pensando", "Estão em modo de economia de energia. Nunca vi um time tão... sereno."),
        ("bia", "neutro", "Um deles roncou. Eu ouvi. Robô de verdade ronca, Professor."),
        ("teo", "suor", "O capitão pediu pra esperar. Ele precisa de mais cinco minutos de sono."),
        ("ambrosio", "cansado", "Eu o compreendo profundamente."),
        ("teo", "pensando", "A gente aproveita pra pegar a bola ou isso é antiesportivo?"),
        ("bia", "neutro", "Antiesportivo é perder pra quem está dormindo. Vai lá."),
        ("ze", "robo", "Bzzzt. (o aspirador liga e acorda um robô adversário sem querer)"),
        ("teo", "susto", "Ops! Foi sem querer!"),
        ("narrador", "neutro", "O robô do Fundão desperta, olha em volta e volta a dormir. O capitão aplaude de olhos fechados."),
        ("bia", "corada", "E, Téo... valeu por ter me chamado. Estou só observando. Só.", ("flag", "bia_convidada")),
    ]},

    "c1_sf_pos": {"bg": "quadra", "cast": ["teo", "ambrosio", "bia"], "lines": [
        ("narrador", "neutro", "Semifinal vencida. O Clube de Teatro se despede com uma reverência de dois minutos e um desmaio dramático."),
        ("teo", "feliz", "Gente, a gente vai pra final!"),
        ("ambrosio", "neutro", "Parabéns. Mas vem aqui, Téo. Reparou nos Impecáveis jogando a outra semifinal?"),
        ("teo", "pensando", "Eles ganharam fácil. Cada robô se mexe exatamente igual ao outro."),
        ("ambrosio", "pensando", "Exatamente. Nenhum erro de passe. Nenhuma derrapada. Nem um desvio de um milímetro."),
        ("teo", "neutro", "Isso é ruim?"),
        ("ambrosio", "pensando", "Robô de verdade tem um tremorzinho, Téo. Uma hesitação. O deles parece desenhado a régua."),
        ("bia", "neutro", "Cronometrei, Professor. Trinta e seis passes, todos com a mesma duração. Até o décimo de segundo."),
        ("ambrosio", "suor", "Trinta e seis passes idênticos? Isso não é futebol. É relógio suíço."),
        ("teo", "pensando", "Vai ver eles treinam muito."),
        ("ambrosio", "triste", "Vai ver, Téo. Vai ver."),
        ("narrador", "neutro", "Do outro lado da quadra, um robô branco pisca duas luzes ciano. Ao mesmo tempo. De novo."),
    ]},

    "c1_final_pre": {"bg": "quadra", "cast": ["teo", "vivi", "ambrosio"], "lines": [
        ("narrador", "neutro", "Final da Copa Interclasses. Quadra lotada. Quatro pessoas torcendo, todas parentes."),
        ("vivi", "convencida", "Então você é o Téo Moreira, o garoto que chegou na final com um aspirador de 1974 e um chinelo."),
        ("teo", "neutro", "O chinelo é estrutural."),
        ("vivi", "convencida", "Valentina Albuquerque, presidente do Grêmio, capitã dos Impecáveis. Meus robôs são patrocinados pela Limpex. Zero defeitos, zero desvios."),
        ("ambrosio", "pensando", "Zero desvios... Robô de verdade sempre tem um defeitinho."),
        ("vivi", "bravo", "O senhor está dizendo que meus robôs são perfeitos demais?"),
        ("ambrosio", "neutro", "Estou dizendo que o meu cheira a fita crepe e o seu cheira a hospital."),
        ("teo", "feliz", "Valentina, a gente só quer jogar bola."),
        ("vivi", "corada", "Não é que eu esteja nervosa. É que você é o único obstáculo estatisticamente relevante deste torneio, e eu detesto surpresas. Prepare-se."),
    ]},

    "c1_final_win": {"bg": "quadra", "cast": ["teo", "vivi", "ambrosio", "bia"], "lines": [
        ("narrador", "neutro", "Apito final. O placar sobe. O Santa Faísca fica em silêncio por três segundos e explode."),
        ("teo", "feliz", "A gente ganhou?! O clube não fecha?!"),
        ("ambrosio", "feliz", "Não fecha! (abraça o Téo, derrubando três canetas e um pão de queijo)"),
        ("vivi", "bravo", "Isso... isso não estava nas minhas projeções. Eu tinha noventa e quatro por cento de chance."),
        ("teo", "suor", "Posso dizer que a rodinha ajudou?"),
        ("vivi", "bravo", "Não pode. Eu li o regulamento. Fita crepe não é item proibido, mas deveria ser."),
        ("teo", "feliz", "O chinelo é estrutural. E decisivo.", ("flag", "chinelo_fica")),
        ("teo", "feliz", "O parafuso foi decisivo! E o chinelo, no coração.", ("noflag", "chinelo_fica")),
        ("teo", "feliz", "Até a Dona Odete torceu. Depois de vender a última coxinha.", ("done", "c1_repescagem")),
        ("bia", "feliz", "Gente, o Zé Poeira fez o gol da vitória de costas. Eu vi."),
        ("vivi", "triste", "Vou treinar. Anotem: isso não se repete. (sai marchando e derruba o troféu de participação)"),
        ("ambrosio", "feliz", "Ela vai voltar. Gente assim sempre volta."),
    ]},

    "c1_final_lose": {"bg": "quadra", "cast": ["teo", "vivi", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O placar não ajuda. O Santa Faísca aplaude com educação, como num recital de flauta."),
        ("vivi", "convencida", "Resultado: Impecáveis, um. Moreira, zero. Era o previsto, mas é sempre bom ver a matemática funcionar."),
        ("teo", "triste", "A gente chegou tão perto..."),
        ("vivi", "neutro", "Perto não é gol. Mas... (desvia o olhar) foi uma boa partida. Estatisticamente aceitável."),
        ("bia", "neutro", "Pera. Isso foi um elogio?"),
        ("vivi", "corada", "Foi uma constatação. Não repita. (sai marchando)"),
        ("ambrosio", "pensando", "Téo, olha o Zé Poeira. Continua girando. Teimoso, que nem o dono."),
        ("ze", "robo", "Bip. Bzzzt. (a rodinha cai e rola até os pés de Vivi, que finge não ter visto)"),
        ("teo", "feliz", "Professor, a gente ainda pode tentar a final de novo?"),
        ("ambrosio", "feliz", "O regulamento diz que sim. Artigo sete, escrito a lápis, ao lado de uma mancha de coxinha."),
    ]},

    "c1_repescagem": {"bg": "cantina", "cast": ["teo", "ambrosio", "gervasio", "bia"], "lines": [
        ("narrador", "neutro", "Eliminados no grupo. O silêncio na arquibancada dura até o sino do recreio."),
        ("teo", "triste", "Acabou. O clube vai fechar. Eu vou ter que vender o chinelo."),
        ("narrador", "neutro", "Dona Odete, a Tia da Cantina, surge com uma bandeja de coxinhas e um regulamento plastificado."),
        ("gervasio", "pensando", "Hum. Artigo três, Regra da Repescagem: quem perde no grupo pode tentar de novo, desde que compre uma coxinha."),
        ("teo", "suor", "Isso está mesmo no regulamento?"),
        ("gervasio", "neutro", "Está. Foi a Dona Odete quem escreveu. E é ela quem manda aqui."),
        ("ambrosio", "feliz", "A Regra da Repescagem salva o clube todo ano. Sempre foi coxinha."),
        ("bia", "neutro", "Eu pago uma. Mas a de frango. A de queijo é pra quem não tem ambição."),
        ("gervasio", "neutro", "Sorteio novo, grupo novo. Tentem não perder de novo, o orçamento de clipes é limitado."),
        ("narrador", "neutro", "A Tia da Cantina carimba o formulário com um carimbo em forma de coxinha. É oficial."),
        {"q": "Que coxinha o Téo compra?", "opts": [
            {"t": "De frango, claro.", "fx": {"flag": "coxinha_frango", "xp_team": 5},
             "reply": [("bia", "feliz", "Finalmente alguém com critério.")]},
            {"t": "De queijo, pelo clube.", "fx": {"flag": "coxinha_queijo", "xp_team": 5},
             "reply": [("bia", "bravo", "Eu avisei que ele não tinha ambição."),
                       ("teo", "feliz", "Ambição é com recheio. Queijo.")]},
        ]},
    ]},

    "c1_end": {"bg": "quadra", "cast": ["teo", "ambrosio", "bia", "vivi", "ze"], "lines": [
        ("narrador", "neutro", "Cerimônia de premiação. O troféu é de plástico, mas o brilho é de ouro de dezoito quilates. Quase."),
        ("teo", "feliz", "Professor, olha! Com o nome do clube gravado! Faltou só o \"b\" em \"robótica\"."),
        ("ambrosio", "feliz", "Detalhe. A gente manda corrigir. Ou deixa assim. Fica histórico."),
        ("vivi", "convencida", "Segunda tentativa. Você teve a sorte de uma repetição, Moreira.", ("done", "c1_final_lose")),
        ("bia", "neutro", "Você me chamou com tanta insistência que fiquei com pena. Estou dentro. Mas a fita é minha.", ("flag", "bia_convidada")),
        ("bia", "neutro", "Você deixou a porta aberta e ninguém me pressionou. Isso é raro. Estou dentro. Mas a fita é minha.", ("noflag", "bia_convidada")),
        ("teo", "feliz", "Bem-vinda ao clube, Bia!"),
        ("ze", "robo", "Bip. Bzzzt. Bip bip. (parece um aplauso. Ou um curto-circuito.)"),
        ("vivi", "neutro", "Moreira. (estende um cartão branco com um raio ciano) Cartão da Limpex. O Dr. Augusto Brilhante quer conhecer você."),
        ("teo", "susto", "A Limpex quer falar com a gente?!"),
        ("vivi", "convencida", "Patrocínio. Eles gostam de talentos. E de coisas limpas. (olha o chinelo) Trabalhe nisso."),
        ("ambrosio", "suor", "Limpex... (guarda o cartão no bolso, junto com as três canetas) Interessante."),
        ("teo", "feliz", "Professor, é a nossa chance! Nosso nome num banner!"),
        ("ambrosio", "pensando", "Hum. Chance. Ou armadilha com laço de fita."),
    ]},

    # ------------------------------------------------------------------ Cap. 2
    "c2_intro": {"bg": "ginasio", "cast": ["teo", "ambrosio", "bia", "dudu", "augusto"], "lines": [
        ("narrador", "neutro", "Taça Vale do Pó. Ginásio Municipal, cheiro de cera de piso e pastel velho. Cinco câmeras, todas operadas pela mesma pessoa."),
        ("dudu", "feliz", "Fala, galera do chat! Estou ao vivo no Ginásio Municipal, com dois espectadores: minha mãe e um bot que só manda \"kkkk\"."),
        ("teo", "neutro", "Quem é esse garoto de headset?"),
        ("bia", "neutro", "Dudu Bits. Transmite a própria vida há três anos. Já narrou até ele escovando os dentes."),
        ("dudu", "feliz", "Sem querer interromper, mas o patrocinador do torneio vai falar. Em holograma, porque presencial é anti-higiênico."),
        ("narrador", "neutro", "Um holograma branco pisca no meio da quadra. Dr. Augusto Brilhante, terno impecável e luvas de látex."),
        ("augusto", "calmo", "Boa tarde, jovens talentos. A Limpex acredita num futuro limpo, eficiente e... (o nariz coça) ...sem poeira."),
        ("augusto", "espirro", "ATCHIM! Desculpem. Foi um holograma de poeira. Não perguntem."),
        ("teo", "pensando", "Ele é alérgico ao próprio holograma?"),
        ("augusto", "calmo", "Sr. Moreira. Vi sua vitória na Interclasses. A Limpex oferece patrocínio: uniformes, peças e um banner de dois metros com a sua cara."),
        ("ambrosio", "suor", "Dois metros... (guarda uma caneta) Cuidado com a letra miúda, Téo."),
        ("augusto", "calmo", "Pensem com carinho. Eu aguardo... (espirra) ...do outro lado do holograma."),
        {"q": "O que o Téo responde ao Dr. Augusto?", "opts": [
            {"t": "Aceitamos o patrocínio da Limpex!", "fx": {"flag": "patroc", "scrap": 100},
             "reply": [("augusto", "calmo", "Excelente. Os uniformes chegam amanhã. Brancos. Muito brancos."),
                       ("dudu", "susto", "Chat, o Téo vendeu a alma! Brincadeira. Vendeu... a camiseta.")]},
            {"t": "Obrigado, mas a gente se vira com fita.", "fx": {"xp_hero": 20},
             "reply": [("bia", "feliz", "Fita crepe nunca deixa na mão. Só na parede."),
                       ("augusto", "calmo", "Decisão... ATCHIM! ...respeitável.")]},
        ]},
    ]},

    "c2_g_gag": {"bg": "ginasio", "cast": ["teo", "bia", "dudu", "ze"], "lines": [
        ("narrador", "neutro", "Segundo jogo do grupo. Os Tios do Churrasco entram com um robô-espeto, um avental e uma caixa de refrigerante. Por segurança."),
        ("dudu", "feliz", "Chat, atenção! A torcida adversária trouxe uma churrasqueira. No ginásio. Alguém avisou o corpo de bombeiros?"),
        ("bia", "suor", "Avisaram. Ele está comendo uma costela na arquibancada."),
        ("teo", "susto", "A fumaça está invadindo o campo! Não consigo ver a bola!"),
        ("ze", "robo", "Bzzzt! (liga a sucção e engole a fumaça. A churrasqueira apaga.)"),
        ("dudu", "susto", "GENTE! O Zé Poeira acabou de aspirar o churrasco inteiro! Isso foi um golpe de gênio ou de fome?"),
        ("bia", "neutro", "Os dois. A fita segurou o filtro, eu juro."),
        ("teo", "feliz", "Eles ficaram sem fumaça e sem moral! É a nossa chance!"),
        ("dudu", "feliz", "Chat, a manchete de hoje: \"aspirador come o churrasco\". Compartilhem!"),
        ("ze", "robo", "Bip. (o filtro cospe um espetinho, ainda quente)"),
        ("teo", "neutro", "Acho que é de frango. Obrigado, Zé."),
    ]},

    "c2_sf_vivi_pre": {"bg": "ginasio", "cast": ["teo", "vivi", "ambrosio", "dudu"], "lines": [
        ("narrador", "neutro", "Semifinal da Taça Vale do Pó. Do outro lado da quadra, um blazer branco passa pelo detector de metais sem apitar."),
        ("vivi", "convencida", "Moreira. Estou aqui pela revanche. Estatisticamente, a segunda partida confirma a primeira."),
        ("teo", "feliz", "Você treinou desde a Interclasses?"),
        ("vivi", "corada", "Não. Quer dizer, sim. Quer dizer, eu só repassei umas planilhas. Nove horas por dia."),
        ("dudu", "feliz", "Chat, a Valentina assumiu publicamente que treina nove horas por dia. Anotem: quarta-feira, 14h."),
        ("vivi", "bravo", "Quem é esse garoto de headset e por que está me filmando?"),
        ("dudu", "suor", "Eu? Eu sou a mídia independente. A mídia independente tem direitos."),
        ("ambrosio", "pensando", "Vivi, os robôs do seu time continuam sem nenhum erro de passe. Isso nunca te pareceu estranho?"),
        ("vivi", "neutro", "Chama-se disciplina, Professor. O senhor devia experimentar."),
        ("ambrosio", "suor", "Eu cochilo desde 1998. Não sei se aguento a disciplina."),
        ("teo", "feliz", "Vamos jogar, Valentina. Sem raiva?"),
        ("vivi", "corada", "Com muita raiva. Mas educada. (ajeita o blazer) Prepare-se."),
    ]},

    "c2_sf_vivi_pos": {"bg": "ginasio", "cast": ["teo", "vivi", "ambrosio", "dudu", "bia"], "lines": [
        ("narrador", "neutro", "Apito final. Os Impecáveis Mk II ficam parados, brancos e brilhando. Ninguém suou. Nem os robôs. Nem a Vivi."),
        ("vivi", "triste", "Perdi de novo. Os números não fecham. Eu conferi três vezes."),
        ("teo", "feliz", "Valentina, foi uma ótima partida!"),
        ("vivi", "bravo", "Não me console. Eu detesto ser consolada. (arruma o cabelo) Mas obrigada."),
        ("bia", "neutro", "Reparei numa coisa. Os robôs dela não suam. Nem aquecem. Nem fazem barulho de esforço."),
        ("dudu", "pensando", "Chat, anotem: temperatura constante de vinte e dois graus em noventa minutos de jogo. Isso é anormal."),
        ("ambrosio", "pensando", "Hum. Zero de calor, zero de desgaste, zero de erro. Estou ficando preocupado."),
        ("vivi", "convencida", "Preocupado com quê? São produtos Limpex. Eles não \"esquentam\". Tem certificado."),
        ("teo", "pensando", "Certificado de quê?"),
        ("vivi", "suor", "...De não esquentar. Eu não li a letra miúda. Deixa pra lá."),
        ("bia", "neutro", "Letra miúda. Sempre ela."),
        ("narrador", "neutro", "Vivi se afasta. Atrás dela, um robô branco ainda pisca duas luzes ciano. Ao mesmo tempo."),
    ]},

    "c2_final_pre": {"bg": "ginasio", "cast": ["teo", "rodolfo", "ambrosio", "dudu", "bia"], "lines": [
        ("narrador", "neutro", "Final da Taça Vale do Pó. O Esquadrão Faxina entra em formação: sincronizados, uniformizados e com cheiro de desinfetante."),
        ("rodolfo", "neutro", "Capitão Rodolfo Pano-de-Chão, Esquadrão Faxina. Eu limpo o que os outros sujam. E vou limpar vocês."),
        ("teo", "suor", "Isso foi uma ameaça ou um serviço?"),
        ("rodolfo", "bravo", "Os dois. O Dr. Augusto manda lembranças. E uma intimação para o chinelo."),
        ("teo", "neutro", "O chinelo é estrutural."),
        ("dudu", "feliz", "Chat! O capanga da Limpex acabou de ameaçar um chinelo ao vivo! Estamos fazendo história!"),
        ("rodolfo", "bravo", "Eu não sou capanga. Sou coordenador de higiene operacional."),
        ("bia", "neutro", "Capanga com cargo. Que chique."),
        ("rodolfo", "neutro", "Aliás, o uniforme novo ficou ótimo, Moreira. Já está quase Limpex.", ("flag", "patroc")),
        ("rodolfo", "neutro", "Aliás, sem uniforme e sem banner. Muita coragem, Moreira. Pouca estampa.", ("noflag", "patroc")),
        ("ambrosio", "pensando", "Capitão, o seu esquadrão rende demais pro orçamento de uma escola. Quem paga?"),
        ("rodolfo", "neutro", "A Limpex paga. E a Limpex é muito generosa. Com quem obedece."),
        ("teo", "feliz", "A gente só quer jogar bola. E ganhar a taça."),
        ("rodolfo", "bravo", "Então joguem. E tentem não deixar rastro. (sai de ré, em linha reta)"),
    ]},

    "c2_final_win": {"bg": "ginasio", "cast": ["teo", "rodolfo", "ambrosio", "dudu", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O Esquadrão Faxina fica em posição de sentido, olhando o placar. Ninguém lhes disse o que fazer quando perdem."),
        ("rodolfo", "susto", "Isso não consta no manual de operações. O manual diz que a gente nunca perde."),
        ("teo", "feliz", "Capitão, foi uma ótima partida!"),
        ("rodolfo", "triste", "Vou ter que escrever um relatório. Onze páginas. A Limpex não gosta de relatório de derrota."),
        ("dudu", "feliz", "Chat, a gente acabou de derrotar a Limpex em campo aberto. Deixa o like."),
        ("bia", "neutro", "E ele ainda vai bater continência pro Zé Poeira."),
        ("rodolfo", "neutro", "(bate continência para o aspirador, rígido) Respeito é respeito. Mas o Dr. Augusto vai saber disso."),
        ("ze", "robo", "Bip. (a rodinha cai e rola até as botas do Capitão, que a devolve com cuidado)"),
        ("ambrosio", "pensando", "Téo, o Capitão tem medo de um relatório. Quem assusta alguém assim não é qualquer um."),
        ("teo", "pensando", "O Dr. Augusto?"),
        ("ambrosio", "neutro", "Ele mesmo. E o holograma dele espirra mais que o original."),
        ("teo", "feliz", "Ganhamos a taça! E o banner de dois metros finalmente cabe na parede.", ("flag", "patroc")),
        ("teo", "feliz", "Ganhamos a taça sem banner e sem uniforme novo. Bem a nossa cara.", ("noflag", "patroc")),
    ]},

    "c2_final_lose": {"bg": "ginasio", "cast": ["teo", "rodolfo", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O Esquadrão Faxina não comemora. Limpa a quadra em formação, centímetro por centímetro."),
        ("rodolfo", "convencido", "Placar: Faxina, vitória. Moreira, derrota. Fim do expediente. Vocês estão dispensados."),
        ("teo", "triste", "A gente quase pegou eles..."),
        ("rodolfo", "neutro", "Quase é o que a Limpex chama de \"fora do orçamento\"."),
        ("bia", "bravo", "Capitão, o senhor tem um espanador no bolso. Eu vi."),
        ("rodolfo", "suor", "É de emergência. Pó é inimigo público. (esconde o espanador atrás das costas)"),
        ("ambrosio", "pensando", "Téo, você ainda pode jogar a final de novo. O regulamento é teimoso, que nem você."),
        ("teo", "feliz", "Então bora de novo, Zé Poeira!"),
        ("ze", "robo", "Bzzzt. Bip. (a rodinha cai. O Capitão a devolve, por reflexo, e depois finge que não fez)"),
        ("rodolfo", "bravo", "Não vi nada. Reportem-se à secretaria. (sai em linha reta, contornando um grão de poeira)"),
    ]},

    "c2_repescagem": {"bg": "cantina", "cast": ["teo", "bia", "dudu", "ambrosio"], "lines": [
        ("narrador", "neutro", "Eliminados no grupo. A arquibancada do ginásio aplaude. Uma pessoa, na verdade. O pai do Téo."),
        ("teo", "triste", "Gente, eu sinto muito. A gente estava indo tão bem."),
        ("dudu", "suor", "Chat, aviso: a transmissão continua. Eu tenho dois espectadores e preciso ser coerente."),
        ("bia", "neutro", "A lanchonete do ginásio vende pastel de feira. A Regra da Repescagem do Vale do Pó diz que quem perde compra um."),
        ("ambrosio", "feliz", "Eu adoro essa regra. Foi um pastelzeiro de Piracicaba que escreveu."),
        ("teo", "pensando", "Todo torneio tem uma regra de comida?"),
        ("bia", "neutro", "Toda regra boa tem. A única coisa que o regulamento ainda não proibiu é comer antes de jogar."),
        ("dudu", "feliz", "Chat, a regra mais justa do país: perdeu, compra pastel e recomeça."),
        ("ambrosio", "cansado", "E se alguém dormir no meio do jogo? Pergunto por experiência."),
        ("teo", "feliz", "Então a gente recomeça com pastel e café! Sorteio novo!"),
        ("narrador", "neutro", "O pastel chega com um guardanapo, uma azeitona e um bilhete: \"Boa sorte, Moreira. Do seu pastelzeiro.\""),
    ]},

    "c2_end": {"bg": "ginasio", "cast": ["teo", "ambrosio", "bia", "dudu", "ze"], "lines": [
        ("narrador", "neutro", "Cerimônia de premiação da Taça Vale do Pó. O troféu é de acrílico, tem o logo da Limpex e uma impressão digital de gordura no canto."),
        ("teo", "feliz", "Professor, a gente ganhou! Dois campeonatos seguidos!"),
        ("ambrosio", "feliz", "Dois! Em trinta anos de clube, é a primeira vez que eu consigo contar até dois."),
        ("dudu", "feliz", "Chat, hoje a live bateu cinquenta pessoas! Cinquenta! Minha mãe até chorou."),
        ("teo", "feliz", "Dudu, quer entrar no clube? A gente precisa de alguém que fale bastante e saiba o que é um cabo."),
        ("dudu", "susto", "Eu?! Entrar numa equipe de verdade? Eu só tenho um robô: o Pixelado."),
        ("dudu", "feliz", "Ele é meio lento, meio pixelado, e tem um bug que o faz girar sempre à esquerda. Mas é meu amigo."),
        ("ze", "robo", "Bip. Bzzzt. (o Zé Poeira gira à esquerda, solidário)"),
        ("bia", "neutro", "Bem-vindo, Dudu. A fita é minha. O Wi-Fi é seu."),
        ("ambrosio", "pensando", "Dudu, guarda toda a telemetria dos jogos. Cada log. Cada gráfico."),
        ("dudu", "suor", "Guardar tudo? Isso eu sei fazer. Tenho cinco pendrives cheios só de memes."),
        ("ambrosio", "pensando", "E o banner da Limpex... Que ele não esconda nada atrás do logo.", ("flag", "patroc")),
        ("ambrosio", "feliz", "Sem patrocínio, sem dever nada a ninguém. Vale mais que um banner.", ("noflag", "patroc")),
    ]},

    # ------------------------------------------------------------------ Cap. 3
    "c3_intro": {"bg": "arena", "cast": ["teo", "ambrosio", "dudu", "augusto", "vivi"], "lines": [
        ("narrador", "neutro", "Estadual Limpex Cup. Arena lotada, telão de vinte metros e o logo da Limpex em tudo. Até no copo de pipoca."),
        ("dudu", "feliz", "Chat, a transmissão chegou a mil espectadores! Mil! Minha mãe trouxe a tia, a vizinha e o cachorro."),
        ("augusto", "calmo", "Senhoras e senhores, a Limpex apresenta o futuro: os Imaculados L-9. (espirra, discretamente) ...Desculpem. Pólen."),
        ("narrador", "neutro", "Cinco robôs brancos entram em formação. Sem poeira, sem barulho e sem uma única risca de graxa."),
        ("vivi", "convencida", "Geração L-9. Lançada ontem. Eles ainda não perderam um jogo. Nem sabem o que é."),
        ("teo", "suor", "Eles não têm nem um arranhão. Como assim?"),
        ("ambrosio", "pensando", "L-9... Esse nome me incomoda. (puxa uma caneta, depois outra)"),
        ("dudu", "pensando", "Chat, vou investigar. A transmissão de hoje continua, mas com o modo detetive ligado."),
        ("augusto", "convencido", "Sr. Moreira, com o uniforme Limpex vocês estão quase apresentáveis. Quase.", ("flag", "patroc")),
        ("augusto", "convencido", "Sr. Moreira, ainda sem uniforme Limpex? Que ousadia. Sem banner e sem pudor.", ("noflag", "patroc")),
        ("teo", "neutro", "A gente vem em paz. E com chinelo."),
        ("vivi", "neutro", "Moreira. Eu não vou torcer pra você. Mas também não vou atrapalhar."),
    ]},

    "c3_g_gag": {"bg": "arena", "cast": ["teo", "bia", "dudu", "ze"], "lines": [
        ("narrador", "neutro", "Segundo jogo do grupo. O Coral Desafinado entra cantando o hino. Cada robô numa nota diferente. Nenhuma certa."),
        ("dudu", "susto", "Chat, protejam os ouvidos. O robô-soprano acabou de quebrar o vidro do placar com um agudo."),
        ("bia", "neutro", "Ele só abriu a tampa do alto-falante. Tecnologia de ponta, usada do jeito errado."),
        ("teo", "suor", "Eu não ouço nada. Meu ouvido está apitando em fá."),
        ("ze", "robo", "Bzzzt. (liga a sucção e engole todos os cacos. Depois, arrota um acorde)"),
        ("dudu", "feliz", "GENTE! O Zé Poeira acabou de arrotar um fá sustenido! Isso é música ou é ameaça?"),
        ("bia", "neutro", "O filtro dele afinou. Eu já falei que dá pra ajustar com fita."),
        ("teo", "feliz", "Se o maestro pedir música ambiente, a gente joga ao som do filtro!"),
        ("narrador", "neutro", "O maestro cede. O estádio inteiro aplaude o arroto. Pela primeira vez, o Coral afina."),
        ("bia", "feliz", "Me avisem quando forem gravar um disco. Eu cobro royalties de fita."),
    ]},

    "c3_logs": {"bg": "camarim", "cast": ["dudu", "teo", "bia", "ambrosio"], "lines": [
        ("dudu", "susto", "Gente, para tudo. Abri a telemetria dos Imaculados. A bateria deles não desce. Nem um por cento, em 90 minutos."),
        ("bia", "neutro", "Será que escondem uma tomada atrás do gol?"),
        ("dudu", "suor", "Pior, Bia. Tem um chip rodando em 400% de overclock. Nome no firmware: HIPERLIMPO X-9, PROTOCOLO TSUNAMI."),
        ("ambrosio", "susto", "Tsunami... Então eles construíram mesmo. (derruba uma das três canetas)"),
        ("teo", "pensando", "O senhor conhece esse chip?"),
        ("ambrosio", "triste", "Fui eu que desenhei o primeiro protótipo. Pedi demissão da Limpex no dia em que descobri pra que ele serviria."),
        ("ambrosio", "neutro", "Overclock sem limite não é tecnologia, Téo. É trapaça com nota fiscal."),
        ("bia", "bravo", "Então é por isso que o robô deles não faz barulho de esforço. Eu achava que era educação."),
        {"q": "O que a equipe faz?", "opts": [
            {"t": "Denunciar agora, com o log do Dudu!", "fx": {"flag": "denuncia"},
             "reply": [("dudu", "suor", "Sem prova pública a Federação arquiva em três dias. Mas eu salvei uma cópia em cinco pendrives.")]},
            {"t": "Ganhar limpo e deixar o placar falar.", "fx": {"flag": "orgulho", "xp_team": 15},
             "reply": [("ambrosio", "feliz", "Orgulho de gente teimosa. Meu favorito.")]},
            {"t": "Primeiro eu preciso comer alguma coisa.", "fx": {"scrap": 15},
             "reply": [("bia", "neutro", "Toma um pão de queijo. Estava no meu bolso desde terça.")]},
        ]},
    ]},

    "c3_sf_pos": {"bg": "arena", "cast": ["teo", "bia", "dudu", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Semifinal vencida. O Sindicato dos Zeladores se despede com um abraço coletivo e um sorteio de rifa."),
        ("teo", "feliz", "Final! A gente vai pra final da Limpex Cup!"),
        ("dudu", "pensando", "Mas eu estava de olho na outra semifinal. Os Imaculados ganharam de seis a zero. Sem trocar de bateria. Sem pausa. Sem respirar."),
        ("bia", "neutro", "Robô não respira, Dudu."),
        ("dudu", "suor", "Eu sei, é força de expressão. Mas o gráfico não tem queda nenhuma. Nem um pico. Nada."),
        ("ambrosio", "pensando", "Um gráfico reto como régua. Isso é assinatura de código, não de máquina."),
        ("dudu", "feliz", "Mandei a cópia do log pra Federação. Ainda sem resposta. A Dra. Helena deve estar comendo pão de queijo.", ("flag", "denuncia")),
        ("ambrosio", "feliz", "Sem denúncia, sem arrependimento. Se for pra ganhar, que seja limpo.", ("flag", "orgulho")),
        ("teo", "pensando", "Então a gente vai enfrentar um robô que nunca cansa."),
        ("bia", "neutro", "Vamos precisar de mais fita. E de pão de queijo. Muito pão de queijo."),
        ("ze", "robo", "Bip. (a rodinha cai e rola até a porta do camarim. Ninguém se surpreende.)"),
    ]},

    "c3_final_pre": {"bg": "arena", "cast": ["teo", "augusto", "vivi", "ambrosio", "bia"], "lines": [
        ("narrador", "neutro", "Final da Estadual Limpex Cup. Setenta mil na arena. Cinco robôs brancos brilham sob o holofote. Nenhum projeta sombra."),
        ("augusto", "calmo", "Sr. Moreira. Seus robôs são, digamos, folclóricos. Os meus são definitivos."),
        ("teo", "neutro", "Os nossos têm personalidade."),
        ("augusto", "convencido", "Personalidade é o nome elegante para defeito de fábrica. (espirra) ATCHIM! A poeira existe, e eu a tolero."),
        ("bia", "bravo", "Defeito de fábrica é robô que não esquenta. Isso, sim, é assustador."),
        ("vivi", "neutro", "Moreira. Eu perguntei sobre os números dos L-9. Disseram que eram confidenciais. Perdi o sono."),
        ("ambrosio", "pensando", "Augusto, o chip dos L-9 nunca foi aprovado pela Federação. Eu sei, fui eu que desenhei."),
        ("augusto", "calmo", "Professor Ambrósio. Sempre tão... histórico."),
        ("teo", "neutro", "A Federação já tem o log. Vai ver o que tem lá.", ("flag", "denuncia")),
        ("teo", "feliz", "A gente vai ganhar limpo e deixar o placar falar.", ("flag", "orgulho")),
        ("augusto", "convencido", "Então joguem. E tentem não sujar a quadra."),
    ]},

    "c3_final_win": {"bg": "arena", "cast": ["teo", "augusto", "ambrosio", "dudu", "bia", "vivi", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O telão mostra o placar. Pela primeira vez na história da Limpex Cup, os robôs brancos não brilham."),
        ("teo", "feliz", "A gente ganhou? Contra os L-9?!"),
        ("dudu", "feliz", "Chat, a transmissão bateu duas mil pessoas! E o gol do Zé Poeira foi aos 89 minutos!"),
        ("augusto", "calmo", "Interessante. Muito interessante. (tira um lenço da luva) O resultado... precisa ser verificado."),
        ("ambrosio", "neutro", "Verificado, Augusto? Você acabou de perder em campo. Isso se chama \"ganhou o outro\"."),
        ("augusto", "convencido", "Em campo \"limpo\". (espirra) ATCHIM! Mas a limpeza, Sr. Moreira, é relativa."),
        ("bia", "bravo", "Sou eu quem vai lavar essa quadra depois. Não me provoca."),
        ("vivi", "triste", "Eles perderam. Eu nunca vi isso. A Limpex sempre ganha."),
        ("teo", "feliz", "Hoje a gente ganhou. Amanhã, quem sabe. Mas hoje a gente ganhou!"),
        ("ze", "robo", "Bip. (a rodinha cai. A arquibancada inteira aplaude a rodinha.)"),
    ]},

    "c3_final_lose": {"bg": "arena", "cast": ["teo", "augusto", "ambrosio", "dudu", "bia", "vivi", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. Os Imaculados L-9 fazem uma reverência sincronizada. Nenhum ofegante. O telão mostra um sorriso corporativo."),
        ("augusto", "calmo", "Limpex, um. Moreira, zero. Um final tão previsível... (espirra) ATCHIM! ...que dá até alergia."),
        ("teo", "triste", "A gente tentou de tudo. Eles não cansam!"),
        ("dudu", "pensando", "Chat, anotem: a bateria deles terminou o jogo em cem por cento. De novo."),
        ("ambrosio", "pensando", "Não é um defeito. É um projeto. E eu conheço o autor."),
        ("bia", "bravo", "Tem que ter um jeito de vencer isso. Perfeito sempre tem ponto fraco."),
        ("vivi", "neutro", "Moreira, não se desanime. (olha pro lado) Foi uma boa partida. Estatisticamente, a melhor que eu vi este ano."),
        ("teo", "feliz", "Obrigado, Valentina. A gente joga a final de novo."),
        ("ambrosio", "feliz", "O regulamento permite. Artigo sete, ao lado de uma mancha de pastel."),
        ("ze", "robo", "Bzzzt. Bip. (a rodinha cai. Os Imaculados fingem não ver. Mas piscam.)"),
    ]},

    "c3_repescagem": {"bg": "cantina", "cast": ["teo", "bia", "dudu", "ambrosio"], "lines": [
        ("narrador", "neutro", "Eliminados no grupo da Estadual. A arena fica em silêncio. Alguém tosse. Era o Dudu, ao vivo."),
        ("dudu", "suor", "Chat... a gente perdeu. Mas a live bateu recorde de espectadores. Isso conta como vitória moral?"),
        ("teo", "triste", "Eu achei que a gente estava pronto."),
        ("bia", "neutro", "Ninguém está pronto. A gente só tem fita e teimosia."),
        ("ambrosio", "feliz", "A Estadual tem um artigo curioso: quem perde no grupo refaz a chave, desde que prove que sabe consertar um robô."),
        ("teo", "pensando", "Isso está mesmo no regulamento?"),
        ("ambrosio", "neutro", "Escrito à mão. Pela Dona Odete. Ela tem um primo na Federação Estadual."),
        ("bia", "feliz", "Então eu conserto o robô do primo. Se ele aceitar fita."),
        ("dudu", "feliz", "Chat, compartilhem a live! Precisamos de mais um espectador!"),
        ("teo", "feliz", "Sorteio novo! Grupo novo! A gente volta."),
        ("narrador", "neutro", "Uma coxinha aparece na mesa, sem remetente. O formulário é carimbado em formato de coxinha. É oficial."),
    ]},

    "c3_end": {"bg": "arena", "cast": ["teo", "augusto", "rodolfo", "ambrosio", "dudu", "bia", "vivi"], "lines": [
        ("narrador", "neutro", "Cerimônia de encerramento da Estadual Limpex Cup. O troféu é dourado, pesado, e a caixa de som solta um chiado alérgico."),
        ("augusto", "calmo", "Em nome da Limpex... (espirra) ATCHIM! ...informo uma decisão difícil."),
        ("augusto", "calmo", "O patrocínio concedido ao clube de robótica está, a partir de agora, rescindido. Os uniformes serão devolvidos até segunda.", ("flag", "patroc")),
        ("augusto", "calmo", "O clube recusou nosso patrocínio, e eu respeitei. Agora a Limpex retira também o apoio ao clube. Nada pessoal.", ("noflag", "patroc")),
        ("teo", "susto", "Rescindido?! Por quê? A gente ganhou a Limpex Cup!"),
        ("rodolfo", "neutro", "Ganharam com uma peça adulterada. O robô Zé Poeira apresentou modificações não homologadas."),
        ("teo", "bravo", "Adulteração? A única coisa adulterada ali é o chinelo!"),
        ("ambrosio", "suor", "Augusto, isso é calúnia. Aquele chip é original, eu..."),
        ("augusto", "convencido", "Professor Ambrósio. Sempre tão histórico. A denúncia será protocolada hoje. O time está suspenso até a audiência."),
        ("dudu", "susto", "Chat, desliga a live... Não, deixa ligada. Isso é história."),
        ("bia", "bravo", "Suspensos?! A gente ganhou limpo!"),
        ("vivi", "triste", "(da arquibancada, em pé, apertando o blazer branco) Eu vi tudo. E não falei nada."),
        ("narrador", "neutro", "No telão, o logo da Limpex pisca. Na arquibancada, uma figura de blazer abaixa a cabeça. E, lá embaixo, o Zé Poeira deixa cair uma rodinha."),
        ("ambrosio", "pensando", "Eles têm medo desse chinelo, Téo. Eu vou descobrir por quê."),
    ]},

    # ------------------------------------------------------------------ Capitulo 4 (Copa Brasil)
    "c4_intro": {"bg": "federacao", "cast": ["teo", "ambrosio", "helena", "dudu", "bia"], "lines": [
        ("narrador", "neutro", "Sede da Federação Nacional de Robótica. Sala de audiência a 16 graus, cadeiras duras e uma samambaia que parece julgar todo mundo."),
        ("helena", "neutro", "Audiência do caso Moreira versus Limpex Corp. Dra. Helena Régis, juíza da Federação. Falem baixo. A samambaia é sensível."),
        ("teo", "susto", "A samambaia está ouvindo?"),
        ("helena", "neutro", "Ela vota. Sr. Moreira, a Limpex acusa seu robô de modificações não homologadas. O que tem a dizer?"),
        ("teo", "neutro", "Entregamos o log do Dudu com o chip X-9 dos Imaculados. Está no processo, página doze.", ("flag", "denuncia")),
        ("dudu", "feliz", "Cinco pendrives, doutora. Um tem a live inteira, com vinheta de abertura.", ("flag", "denuncia")),
        ("teo", "feliz", "A gente prefere provar em campo. Sem papelada. Deixa o placar falar.", ("flag", "orgulho")),
        ("ambrosio", "pensando", "Doutora, o chip do Zé Poeira tem mais de vinte anos. É original. Eu poderia mostrar a nota fiscal, mas ela ficou com o Augusto."),
        ("helena", "neutro", "Sem o documento, não posso liberar o time sem condições. Decisão: o time volta, mas passa pela Vistoria antidoping antes de cada jogo."),
        ("bia", "suor", "Vistoria? Vão abrir os nossos robôs? Tem fita crepe lá dentro. E um pão de queijo de terça."),
        ("helena", "neutro", "Será registrado como material orgânico não identificado. Uma inspetora acompanhará a equipe na Copa Brasil."),
        ("teo", "feliz", "Aceitamos! Quem não deve não teme. Só o chinelo teme."),
        ("helena", "neutro", "Audiência encerrada. A samambaia aprovou. Ela raramente aprova."),
    ]},

    "c4_g_vistoria": {"bg": "estadio", "cast": ["teo", "bia", "helena", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Estádio Nacional. Antes do segundo jogo, a Vistoria: um scanner do tamanho de uma geladeira e uma fila de robôs constrangidos."),
        ("helena", "neutro", "Cada robô passa pelo detector antidoping. Sem exceção. Nem a mascote do estádio."),
        ("bia", "suor", "Doutora, o Zé Poeira vai passar? Ele tem um chinelo e fita crepe. Vai apitar tudo."),
        ("ze", "robo", "Bzzzt. (o scanner apita. Depois apita de novo. Depois pede desculpas.)"),
        ("helena", "neutro", "Leitura: chinelo, fita, mofo e uma moeda de dez centavos. Alguma modificação eletrônica ilegal? Nenhuma."),
        ("teo", "feliz", "A moeda é de sorte!"),
        ("helena", "neutro", "Registrada como amuleto. Aprovado."),
        ("ambrosio", "pensando", "Curioso. O scanner nunca viu um chip tão antigo. Classificou como relíquia."),
        ("bia", "neutro", "Chamou o chinelo de relíquia também. Eu ouvi."),
        ("ze", "robo", "Bip. (o scanner imprime um recibo: \"Obrigado pela visita\".)"),
        ("teo", "feliz", "Até o scanner gostou dele."),
    ]},

    "c4_vivi_break": {"bg": "estadio", "cast": ["teo", "vivi", "augusto", "ambrosio", "bia"], "lines": [
        ("narrador", "neutro", "Corredor do Estádio Nacional. O Dr. Augusto cumprimenta a Vivi com o cotovelo, por higiene. Ela não retribui."),
        ("vivi", "bravo", "Senhor Augusto. Li o código do X-9. Quatrocentos por cento de overclock. O senhor disse que meus robôs eram apenas bem projetados."),
        ("augusto", "calmo", "E são. (espirra) ATCHIM! Bem projetados e... bem otimizados."),
        ("vivi", "bravo", "Otimizados contra o regulamento. Perdi duas finais e achei que o erro era meu. Conferi as planilhas três vezes!"),
        ("augusto", "convencido", "Valentina, você é uma excelente presidente de Grêmio. Seria uma pena perder o patrocínio."),
        ("vivi", "neutro", "Eu li o log que o Dudu mandou à Federação. Assinei como testemunha ontem à noite. Sem avisar ninguém.", ("flag", "denuncia")),
        ("vivi", "neutro", "O Moreira disse que ia ganhar limpo e deixar o placar falar. Eu quero estar do lado do placar.", ("flag", "orgulho")),
        ("vivi", "neutro", "(tira o broche da Limpex do blazer e põe na mão dele) Considere perdido. Eu rompo a parceria."),
        ("augusto", "espirro", "ATCHIM! Isso é... um broche com poeira?!"),
        ("augusto", "convencido", "Você vai se arrepender, Valentina."),
        ("vivi", "triste", "Já me arrependi. De ter demorado tanto."),
        ("vivi", "corada", "Moreira... Professor... posso entrar na equipe de vocês? Eu trago planilhas."),
        ("teo", "feliz", "Claro! A gente tem um chinelo e um pão de queijo de terça."),
        ("bia", "neutro", "Bem-vinda. Traga fita."),
    ]},

    "c4_sf_pre": {"bg": "estadio", "cast": ["teo", "rodolfo", "ambrosio", "bia"], "lines": [
        ("narrador", "neutro", "Semifinal da Copa Brasil. Uma fileira de robôs prateados entra em campo. Estão tão alinhados que a régua ficou com vergonha."),
        ("rodolfo", "neutro", "Capitão Rodolfo, agora comandante da Divisão Platinum. Promoção. Troquei o rodo por uma prancheta."),
        ("teo", "feliz", "Parabéns, Capitão! A prancheta é nova?"),
        ("rodolfo", "neutro", "É. Tem até caneta. (olha pro Prof.) Três, aliás. Eu copiei o estilo."),
        ("ambrosio", "suor", "Não mexe nas minhas canetas."),
        ("rodolfo", "neutro", "Hoje joga a Platinum Reserva, o time que treina quem treina. Eu só vim ver o aquecimento."),
        ("bia", "neutro", "Quem aquece um robô que não esquenta?"),
        ("rodolfo", "convencido", "Aquece o regulamento. (pausa) Boa sorte. Não vai adiantar, mas boa sorte."),
        ("teo", "pensando", "Ele está sendo educado. Isso me assusta."),
        ("ambrosio", "pensando", "A Federação certamente vai olhar o time dele com o mesmo cuidado. Certamente."),
    ]},

    "c4_sf_pos": {"bg": "estadio", "cast": ["teo", "bia", "helena", "ambrosio", "dudu"], "lines": [
        ("narrador", "neutro", "Apito final. A Platinum Reserva sai de campo em fila indiana, sem uma gota de óleo. Quem limpou o gramado foi o Zé Poeira."),
        ("teo", "feliz", "A gente está na final da Copa Brasil! Eu quase não acredito!"),
        ("dudu", "feliz", "Chat, atenção: o time do Téo avançou para a final. Meu pai ligou. Ele nunca liga."),
        ("helena", "neutro", "Resultado da Vistoria: os robôs da Reserva passaram em todos os testes. Chip em repouso, nenhuma irregularidade."),
        ("ambrosio", "pensando", "Em repouso, doutora. Esse é o ponto. Um chip que só liga em jogo não aparece no scanner."),
        ("helena", "pensando", "Prof. Ambrósio, está me pedindo para desconfiar da minha própria máquina?"),
        ("ambrosio", "suor", "Estou pedindo para ela tirar uma soneca. Ela merece."),
        ("bia", "neutro", "Doutora, a máquina de lá dá um apito de quatro segundos quando vê o chinelo. Eu cronometrei."),
        ("helena", "neutro", "Anotado. Vou providenciar um scanner atualizado. Para o Mundial, talvez."),
        ("teo", "pensando", "Um Mundial. Eu ainda não consigo imaginar um Mundial de aspiradores."),
    ]},

    "c4_final_pre": {"bg": "estadio", "cast": ["teo", "rodolfo", "vivi", "ambrosio", "bia", "helena"], "lines": [
        ("narrador", "neutro", "Final da Copa Brasil. Oitenta mil lugares, quarenta e dois deles ocupados por famílias do Dudu."),
        ("rodolfo", "convencido", "Divisão Platinum, formação cinco-zero-zero. Tudo atacante, nenhum defeito. Treinamos com o manual da Limpex, encadernado."),
        ("vivi", "bravo", "Rodolfo, você era o capanga do rodo. Agora tem pose de CEO."),
        ("rodolfo", "neutro", "Valentina. Está do lado errado do banco."),
        ("vivi", "convencida", "Estou do lado certo do placar. Agora eu faço as planilhas deles, só que ao contrário."),
        ("teo", "feliz", "Valentina, você está de camiseta velha!"),
        ("vivi", "corada", "É... confortável. Não conta pra ninguém."),
        ("helena", "neutro", "Vistoria da final: os robôs da Platinum estão limpos. Os da equipe Moreira estão sujos. Por motivos de graxa."),
        ("bia", "feliz", "Graxa de qualidade. Eu seleciono."),
        ("ambrosio", "pensando", "Rodolfo, quando a bateria deles ficar em cem por cento, pense na pessoa que você é."),
        ("rodolfo", "neutro", "Eu sou a pessoa que vai ganhar. Vamos começar."),
    ]},

    "c4_final_win": {"bg": "estadio", "cast": ["teo", "rodolfo", "vivi", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O estádio inteiro faz silêncio e, depois, um barulho enorme. Um aspirador com um chinelo acabou de ganhar a Copa Brasil."),
        ("teo", "susto", "A gente ganhou?! A gente ganhou da Platinum?!"),
        ("vivi", "feliz", "Estatisticamente impossível. Confirmo: aconteceu."),
        ("bia", "feliz", "Eu falei que a fita segura! X"),
        ("rodolfo", "neutro", "Eu... (ajeita a prancheta) ...parabéns, Moreira. A Platinum não perdeu. Foi um erro de cálculo."),
        ("ambrosio", "feliz", "É o nome elegante de derrota, Rodolfo."),
        ("rodolfo", "triste", "O Dr. Augusto vai ficar furioso. Ele espirra quando fica furioso."),
        ("teo", "neutro", "Ele espirra o tempo todo."),
        ("rodolfo", "convencido", "Hoje vai ser pior. (olha para o relógio) Eu preciso ir. A prancheta tem horário."),
        ("ze", "robo", "Bzzzt. (a rodinha esquerda cai. O estádio cantou parabéns à rodinha.)"),
    ]},

    "c4_final_lose": {"bg": "estadio", "cast": ["teo", "rodolfo", "vivi", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. A Divisão Platinum se alinha em formação cinco-zero-zero. Os robôs cumprimentam a bola. A bola não responde."),
        ("rodolfo", "convencido", "Placar final: Platinum, vitória. Quem diria. Eu limpei todo mundo."),
        ("teo", "triste", "A gente tentou de tudo. O robô deles nem sua!"),
        ("vivi", "pensando", "Analisei os passes: tempo de reação de dois milésimos. Não é humano. Nem é de robô honesto."),
        ("bia", "bravo", "Perfeito demais é suspeito. Eu sei, eu fui perfeita uma vez. Foi na segunda série."),
        ("ambrosio", "pensando", "Rodolfo, o chip dos seus robôs só liga em jogo. Eu sei, o desenho é meu."),
        ("rodolfo", "neutro", "O senhor desenhou. Ele não sabe de nada. Eu também não. Tenha um bom dia."),
        ("teo", "feliz", "Valentina, na próxima a gente joga a final de novo, não é?"),
        ("vivi", "convencida", "O regulamento permite. Eu li três vezes. Eu leio tudo três vezes."),
        ("ze", "robo", "Bip. (a rodinha cai. O Rodolfo finge não ver. Ele vê.)"),
    ]},

    "c4_repescagem": {"bg": "cantina", "cast": ["teo", "bia", "dudu", "ambrosio", "vivi"], "lines": [
        ("narrador", "neutro", "Eliminados no grupo da Copa Brasil. A cantina do estádio vende um pastel que, dizem, também foi eliminado."),
        ("dudu", "suor", "Chat, a gente caiu. Mas o pastel está ótimo. Isso é um relatório honesto."),
        ("teo", "triste", "Eu achei que a Vistoria fosse nos dar sorte."),
        ("bia", "neutro", "A Vistoria só deu um papel carimbado dizendo que a gente é pobre. É uma boa lembrança."),
        ("vivi", "pensando", "Revisei as planilhas do grupo. A gente precisa de mais posse de bola. E de menos pastel."),
        ("ambrosio", "feliz", "Regulamento da Copa Brasil, artigo nove: quem cai no grupo refaz a chave se pagar o pastel de todo mundo."),
        ("teo", "susto", "Isso está mesmo no regulamento?"),
        ("ambrosio", "neutro", "Escrito a caneta. Das três que eu tenho. Então, é lei."),
        ("dudu", "feliz", "Chat, compartilhem! Vamos ressarcir um pastel!"),
        ("teo", "feliz", "Sorteio novo! Grupo novo! A gente volta."),
        ("vivi", "corada", "Eu pago o pastel. Mas só porque esses cálculos me deram fome."),
    ]},

    "c4_end": {"bg": "estadio", "cast": ["teo", "vivi", "ambrosio", "bia", "dudu", "helena", "ze"], "lines": [
        ("narrador", "neutro", "Fim da Copa Brasil. O estádio esvazia devagar, as luzes caem e um gari muito feliz varre o confete."),
        ("helena", "neutro", "Resultado da Vistoria final: equipe Moreira aprovada. A Federação reconhece que não há adulteração. Suspensão cancelada."),
        ("teo", "feliz", "Obrigado, doutora! E obrigado, samambaia!"),
        ("vivi", "corada", "Então, oficialmente... eu me inscrevo. Valentina Albuquerque, ex-presidente de Grêmio. E este é o Majestade."),
        ("narrador", "neutro", "O Majestade, um Titã azul-marinho de duas toneladas simbólicas, se aproxima devagar. Cada passo faz o chão tremer. O Dudu filma o chão."),
        ("bia", "feliz", "Que robô lindo! Posso colocar um adesivo?"),
        ("vivi", "bravo", "Não. (pausa) ...Um adesivo pequeno."),
        ("ambrosio", "triste", "Téo, está na hora de contar uma coisa. Eu, seu avô Nestor e o Augusto fundamos a Limpex numa garagem, trinta anos atrás."),
        ("teo", "susto", "Os três? O meu avô fundou a Limpex?!"),
        ("ambrosio", "neutro", "O Nestor desenhou o corpo, eu escrevi o software e o Augusto cuidou da papelada. Foi aí que o Augusto virou outra pessoa."),
        ("bia", "pensando", "Falando em software, o Zé Poeira apitou no scanner de novo. Tem alguma coisa na placa dele."),
        ("narrador", "neutro", "A Bia abre o painel do Zé Poeira. Entre três clipes, um chiclete e um bilhete de loteria de 2004, há um chip antigo, embrulhado em flanela."),
        ("ambrosio", "feliz", "O chip original. \"Chip do Vovô\". Legal, estável, e com um limite de bateria que respeita a física."),
        ("ze", "robo", "Bzzzt. Bip. (a rodinha cai. Dessa vez, alguém pega e entrega de volta.)"),
    ]},

    # ------------------------------------------------------------------ Capitulo 5 (Mundial)
    "c5_intro": {"bg": "mundial", "cast": ["teo", "ambrosio", "vivi", "bia", "dudu"], "lines": [
        ("narrador", "neutro", "Arena Global de Neo-Tóquio. Doze horas de voo, três escalas, um jet lag e uma mala que o Zé Poeira abriu sozinho. Em pleno corredor."),
        ("teo", "cansado", "Que horas são? Aqui é de manhã? Meu corpo acha que é terça."),
        ("dudu", "feliz", "Chat, bom dia, boa tarde e boa noite! Estou ao vivo de Neo-Tóquio, onde o elevador fala com sotaque e o banheiro tem dezessete botões."),
        ("bia", "susto", "Dudu, não aperte os botões. Eu apertei o terceiro e agora o chuveiro canta."),
        ("vivi", "convencida", "Fiz um cronograma de adaptação ao fuso: sono, hidratação e revisão tática. Cada item em verde."),
        ("teo", "pensando", "E o item vermelho?"),
        ("vivi", "corada", "O sorvete de feijão azuki. Que eu comi três vezes. Eu estou em crise."),
        ("ambrosio", "cansado", "Ontem eu dormi em pé na fila do hotel. Acordei, pedi desculpas, e estava falando com uma estátua."),
        ("narrador", "neutro", "No telão do saguão, o logo da Limpex pisca. Ao lado, um cartaz: \"Hiperlimpos X-9: o futuro é sem poeira\"."),
        ("teo", "neutro", "O futuro é sem poeira. Eu gostaria de um futuro com um pouco de poeira. Só para ter graça."),
        ("ambrosio", "pensando", "Poeira é prova de que alguém viveu aqui, rapaz. Guarde essa frase. Escreva num guardanapo."),
        ("bia", "feliz", "Eu escrevi no guardanapo e na manga. É o meu melhor trabalho."),
    ]},

    "c5_g1_gag": {"bg": "mundial", "cast": ["teo", "bia", "dudu", "kenji", "ze"], "lines": [
        ("narrador", "neutro", "Primeiro jogo do grupo: Sakura Vacuum Club. Os robôs entram em campo, fazem uma reverência de noventa graus e esperam. Educados demais."),
        ("kenji", "feliz", "Bem-vindos ao Mundial! Eu sou Kenji, do Dojo. Hoje só observo, mas desejo uma partida honrada."),
        ("teo", "feliz", "Obrigado, Kenji! A gente também deseja. Honra e... fita."),
        ("bia", "neutro", "Eles se curvaram para a bola. A bola se curvou de volta. Eu vi."),
        ("dudu", "feliz", "Chat, os robôs do Sakura estão pedindo licença para fazer o gol. Isso é tão fofo que eu quase perdi a narração."),
        ("teo", "susto", "Estão pedindo licença?! Eles fazem uma reverência antes de chutar!"),
        ("ze", "robo", "Bzzzt! (liga a sucção e leva a bola, a licença e uma flor de cerejeira.)"),
        ("kenji", "susto", "Ele fez o gol sem pedir licença! Que audácia! Que... eficiente!"),
        ("bia", "neutro", "É o estilo dele. Em casa ele também não pede."),
        ("teo", "feliz", "Mil desculpas, Sakura! Obrigado pela partida!"),
        ("dudu", "feliz", "Chat, a manchete: \"aspirador pede perdão e faz gol\". Compartilhem!"),
    ]},

    "c5_g2_gag": {"bg": "mundial", "cast": ["teo", "bia", "dudu", "ze", "ambrosio"], "lines": [
        ("narrador", "neutro", "Segundo jogo: Staubsauger Sporting. O árbitro tem um cronômetro, uma régua e a expressão de quem já foi pontual a vida inteira."),
        ("dudu", "feliz", "Chat, atenção! A partida começa às quinze horas, zero minutos e zero segundos. Se alguém espirrar, perde um ponto."),
        ("teo", "susto", "Um ponto por espirro? O Dr. Augusto não ia sobreviver ao primeiro tempo."),
        ("bia", "suor", "Eles estão passando com uma flanela nos robôs. Antes, durante e depois do gol. Em intervalos regulares."),
        ("ambrosio", "pensando", "Boa organização. Se nós nos organizássemos assim, eu não teria perdido minhas canetas em 1998."),
        ("ze", "robo", "Bzzzt. (a rodinha cai exatamente três segundos depois do apito. O árbitro anota.)"),
        ("dudu", "feliz", "Cartão amarelo para o Zé Poeira por atraso involuntário de rodinha!"),
        ("teo", "neutro", "Isso está no regulamento deles?"),
        ("ambrosio", "neutro", "Estava na página trezentos e quatro. Eu cochilei na hora e li assim mesmo."),
        ("bia", "feliz", "Peguem a rodinha! Ela é uma prova de que a gente chegou cedo."),
        ("teo", "feliz", "Depois do jogo, a gente passa uma flanela em tudo. Prometo."),
    ]},

    "c5_g3_gag": {"bg": "mundial", "cast": ["teo", "bia", "dudu", "vivi", "ze"], "lines": [
        ("narrador", "neutro", "Terceiro jogo: Les Aspirateurs. No minuto vinte, os adversários param o jogo. Um deles traz uma bandeja com um croissant e uma xícara."),
        ("dudu", "susto", "Chat, é intervalo para o café! Estão tomando o café no meio do primeiro tempo! Isso é permitido?"),
        ("vivi", "convencida", "Regulamento, artigo catorze: pausas culturais não podem passar de oito minutos. Eu li três vezes."),
        ("bia", "neutro", "Eles ofereceram um croissant pro Zé Poeira. Ele aspirou. O croissant, a xícara e a bandeja."),
        ("teo", "susto", "Zé! Devolva a bandeja!"),
        ("ze", "robo", "Bip. (cospe só a xícara. A xícara está limpa, brilhando e com um bilhete: \"merci\".)"),
        ("dudu", "feliz", "O goleiro adversário entrou em greve porque a bola estava fora da hora do almoço!"),
        ("vivi", "pensando", "Greve do goleiro. Em plena Copa. Isso nunca aconteceu nas minhas planilhas."),
        ("teo", "feliz", "Vamos cumprimentar o capitão deles. Bonjour! Obrigado!"),
        ("bia", "neutro", "Ele só respondeu \"oui\". Para qualquer pergunta. Eu perguntei se ele tinha fita. Oui."),
        ("dudu", "feliz", "Chat, vou fazer um quiz. Quem sabe o que é \"oui\" em português? Todos já sabem. Ok."),
    ]},

    "c5_qf_pre": {"bg": "mundial", "cast": ["teo", "bia", "dudu", "vivi", "ambrosio"], "lines": [
        ("narrador", "neutro", "Quartas de final: Dust Bunnies USA. Uma banda toca o hino, um canhão solta confete e uma mascote gigante, em forma de coelho de poeira, abraça todo mundo."),
        ("teo", "susto", "Alguém pode pedir pra ele me soltar? Ele está me abraçando há dois minutos."),
        ("bia", "neutro", "Ele abraça o time inteiro antes de cada jogo. É a tática. Eu li no panfleto."),
        ("dudu", "feliz", "Chat, o coelho de poeira tem trinta mil seguidores! Eu tenho dois. Quero ser o coelho."),
        ("vivi", "bravo", "Dudu, concentre-se. Os Dust Bunnies lideram o grupo deles com folga. Os robôs são grandes, rápidos e barulhentos."),
        ("ambrosio", "pensando", "Barulhentos é bom sinal. Robô que faz barulho é robô que se esforça. Os do Augusto ficam em silêncio."),
        ("teo", "pensando", "Então, se o robô faz barulho, ele é honesto?"),
        ("ambrosio", "feliz", "Quase sempre. Exceto o meu despertador."),
        ("vivi", "convencida", "Moreira, eles têm uma jogada de pipoca: um chute que parece fraco e vira um torpedo. Marcação dupla no meio."),
        ("teo", "feliz", "Marcação dupla no meio! E uma pipoca pra Bia, que ela merece."),
        ("bia", "feliz", "Eu aceito. Mas só se vier com sal e fita."),
    ]},

    "c5_qf_pos": {"bg": "mundial", "cast": ["teo", "bia", "dudu", "vivi", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. A arena inteira canta, o coelho de poeira chora fantasiado e a banda improvisa uma música com cinco notas e muito entusiasmo."),
        ("dudu", "feliz", "Chat, a gente está na semifinal do Mundial! Eu quase caí do assento. Perdi um fone de ouvido, mas ganhei uma semifinal."),
        ("teo", "feliz", "A gente venceu os Dust Bunnies! Eu nem acredito!"),
        ("vivi", "convencida", "Eu acredito. Estava na minha terceira planilha, coluna quatro, linha vinte."),
        ("bia", "neutro", "Ela errou duas casas decimais. Mas deu certo."),
        ("vivi", "corada", "Erro de digitação. Aconteceu uma vez. Duas. Cinco."),
        ("narrador", "neutro", "O coelho de poeira passa por eles. Ele entrega um buquê de pipoca e uma foto autografada com a assinatura de um rabisco."),
        ("teo", "feliz", "Obrigado, coelho! Eu guardo com carinho!"),
        ("ze", "robo", "Bzzzt. (aspira a pipoca. Em seguida, devolve a pipoca. Uma por uma.)"),
        ("dudu", "susto", "Chat, ele separou a pipoca por tamanho! Isso é obsessão ou ternura?"),
    ]},

    "c5_sf_kenji": {"bg": "mundial", "cast": ["teo", "kenji", "bia", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Semifinal do Mundial. Do outro lado do campo, o Dojo do Kenji entra em formação. Um robô carrega uma plantinha de bonsai nas costas."),
        ("kenji", "feliz", "Téo! Que honra dividir um campo com você. Eu vi todos os seus jogos. Até o do chinelo."),
        ("teo", "feliz", "Kenji! Eu vi o seu da semana passada. Aquele passe de calcanhar foi lindo!"),
        ("kenji", "neutro", "Foi acidente. O robô tropeçou, a bola quicou, o goleiro adversário desmaiou de emoção. Eu chamei de estratégia."),
        ("bia", "feliz", "A gente chama de gambiarra. Mesma coisa, só com mais fita."),
        ("ambrosio", "feliz", "Kenji, jovem. Seu avô me ensinou a dobrar origami. Eu nunca consegui. Ele diz que é falta de paciência."),
        ("kenji", "feliz", "Meu avô diz que o senhor tem um talento raro: cochilar em pé durante o hino."),
        ("ambrosio", "suor", "Foi só uma vez. Ou três."),
        ("kenji", "neutro", "Téo, hoje eu vou dar o meu melhor. Se eu perder, quero perder para alguém que respeita a bola."),
        ("teo", "feliz", "E se eu perder, quero perder para alguém que me ensinou o calcanhar."),
        ("kenji", "feliz", "Combinado. (faz uma reverência) Que vença o robô que ouvir melhor a quadra."),
        ("ze", "robo", "Bzzzt. (a rodinha cai. O bonsai se inclina em respeito. Um respeito silencioso.)"),
    ]},

    "c5_final_pre": {"bg": "mundial", "cast": ["teo", "augusto", "vivi", "ambrosio", "ze"], "lines": [
        ("narrador", "neutro", "Final do Mundial. Cinquenta mil pessoas, trezentos drones de câmera e um forte cheiro de desinfetante de lavanda."),
        ("augusto", "calmo", "Sr. Moreira. Fundei a Limpex com uma ideia simples: o mundo é sujo, e a perfeição é a única resposta."),
        ("teo", "neutro", "O senhor é alérgico a poeira, né?"),
        ("augusto", "espirro", "ATCHIM! ... Isso não vem ao caso."),
        ("vivi", "bravo", "Eu li o código do X-9, senhor Augusto. O senhor me disse que era \"só uma otimização\"."),
        ("augusto", "convencido", "E é. De quatrocentos por cento."),
        ("ambrosio", "triste", "Augusto, nós três começamos naquela garagem. O Nestor desenhou o corpo. Eu, o software. Você, a nota fiscal."),
        ("augusto", "calmo", "E hoje eu sou o único dos três com um helicóptero."),
        ("teo", "feliz", "O Zé Poeira tem um chinelo. E o chip original do meu avô, que respeita o limite da bateria."),
        ("augusto", "calmo", "Então descobriremos quanto vale uma roda a menos contra uma roda a mais."),
        ("ze", "robo", "Bzzzt. (a rodinha esquerda cai. Ninguém comenta.)"),
    ]},

    "c5_final_win": {"bg": "mundial", "cast": ["teo", "augusto", "vivi", "ambrosio", "bia", "dudu", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. O placar do Mundial pisca. Cinquenta mil pessoas prendem a respiração. Os drones de câmera giram, confusos."),
        ("dudu", "susto", "Chat... chat... a gente... a gente ganhou o Mundial! Eu preciso sentar. Eu estou sentado. Eu preciso sentar de novo."),
        ("teo", "susto", "A gente é campeão?! Com o chinelo?!"),
        ("bia", "feliz", "Com o chinelo e com a fita! Eu avisei a fita!"),
        ("vivi", "corada", "Estatisticamente... não, deixa. Eu estou feliz. Pronto. Está dito."),
        ("augusto", "calmo", "O resultado é contestável. O X-9 estava fora de calibragem. (espirra) ATCHIM! Foi o vento."),
        ("ambrosio", "neutro", "Augusto, estamos em um estádio fechado. Não há vento."),
        ("augusto", "convencido", "Então foi a poeira. Há sempre poeira em algum lugar. É por isso que eu a odeio."),
        ("teo", "feliz", "A poeira só quer ser notada. Como o Zé Poeira."),
        ("ze", "robo", "Bip. (a rodinha cai. O estádio aplaude a rodinha, de pé.)"),
        ("narrador", "neutro", "Nesse instante, uma figura de blazer roxo atravessa o gramado com uma pasta. É a Dra. Helena Régis. E ela trouxe o scanner novo."),
    ]},

    "c5_final_lose": {"bg": "mundial", "cast": ["teo", "augusto", "vivi", "ambrosio", "bia", "ze"], "lines": [
        ("narrador", "neutro", "Apito final. Os Hiperlimpos X-9 fazem uma reverência sincronizada. Trinta segundos depois, ainda estão com a bateria em cem por cento."),
        ("augusto", "calmo", "Limpex, vitória. Moreira, derrota. (espirra) ATCHIM! Chamarei isso de ordem natural das coisas."),
        ("teo", "triste", "A gente deu tudo. Eles nem suaram. Nem transpiraram. Nem... Eu não sei."),
        ("bia", "bravo", "Nada é invencível, Téo. Nem a Limpex. Nem a Santa Faísca, que fechou o refeitório por causa de um pastel."),
        ("vivi", "pensando", "Registrei todas as jogadas. O X-9 repete um padrão a cada onze segundos. Se eu quebrar a repetição, ele quebra."),
        ("ambrosio", "pensando", "Você achou a brecha do algoritmo. Eu desenhei aquela rotina em 1998. Eu esqueci de uma cláusula."),
        ("teo", "pensando", "Que cláusula?"),
        ("ambrosio", "feliz", "A que diz: se o adversário insistir, repita. Ele tem um limite. A gente só precisa insistir mais."),
        ("teo", "feliz", "Revanche! Mais uma vez!"),
        ("ze", "robo", "Bzzzt. Bip. (a rodinha cai. Dessa vez, o Augusto também olha. Por um instante.)"),
    ]},

    "c5_antidoping": {"bg": "mundial", "cast": ["teo", "augusto", "helena", "ambrosio", "vivi", "dudu", "rodolfo"], "lines": [
        ("narrador", "neutro", "Gramado da Arena Global. Um scanner novo, do tamanho de um carro pequeno, entra rolando. Alguém colou um adesivo de coelho nele."),
        ("helena", "neutro", "Federação Mundial de Robótica, Vistoria final. Inspeção ao vivo do Hiperlimpos X-9, em rede global. Dr. Augusto, por favor, afaste-se."),
        ("augusto", "calmo", "Doutora, isso é um absurdo. Um scanner com adesivo de coelho não é um instrumento científico."),
        ("helena", "neutro", "É o instrumento que revela chips ligados em jogo. Foi instalado ontem. O adesivo é uma homenagem."),
        ("dudu", "feliz", "Chat, atenção! A transmissão de agora bate duzentos mil espectadores! Todo mundo está vendo!"),
        ("narrador", "neutro", "O scanner apita. Depois apita mais forte. No telão, o log aparece: \"Overclock 400%. Protocolo Tsunami. Bateria: infinita.\""),
        ("helena", "bravo", "Dr. Augusto Brilhante. A Limpex Corp está desclassificada e todos os seus títulos serão revistos. Inclusive os de ontem."),
        ("augusto", "espirro", "ATCHIM! Isso é uma calúnia! Eu sou um homem limpo! Eu sou... ATCHIM! ...alérgico à injustiça!"),
        ("rodolfo", "triste", "Doutor, eu sempre soube que o X-9 era trapaça. Só não quis ouvir. Peço demissão. E devolvo a prancheta."),
        ("vivi", "neutro", "Eu fui testemunha. Está tudo gravado. Tem até a parte em que o senhor espirra no meio da confissão."),
        ("ambrosio", "feliz", "Perfeição que precisa de overclock não é perfeição. É maquiagem com nota fiscal."),
        ("teo", "feliz", "Quer dizer que o título é nosso de verdade?"),
        ("helena", "neutro", "É. A samambaia também aprovou. Por videoconferência."),
    ]},

    "c5_repescagem": {"bg": "cantina", "cast": ["teo", "bia", "dudu", "ambrosio", "vivi"], "lines": [
        ("narrador", "neutro", "Eliminados no grupo do Mundial. O hotel serve um café da manhã com onze tipos de arroz. Ninguém tem apetite. Quase."),
        ("dudu", "suor", "Chat, a gente caiu. Mas a hashtag da nossa torcida está em quarto lugar mundial. Entre o sushi e o coelho."),
        ("teo", "triste", "A gente veio tão longe."),
        ("bia", "neutro", "A gente veio tão longe com tanta fita. É um recorde de fita internacional."),
        ("vivi", "pensando", "Analisei: perdemos no detalhe. A gente fez posse demais e finalizou de menos. Corrijo na próxima."),
        ("ambrosio", "feliz", "Regulamento do Mundial, artigo vinte e dois: quem cai no grupo refaz a chave se pedir desculpas ao pastel."),
        ("teo", "susto", "O pastel de novo?!"),
        ("ambrosio", "neutro", "É uma tradição. Todo campeonato tem um pastel. Esse está num cartaz. Lá no corredor."),
        ("dudu", "feliz", "Chat, vou ao corredor pedir desculpas ao pastel. Ao vivo."),
        ("teo", "feliz", "Sorteio novo! Grupo novo! A gente volta."),
        ("bia", "feliz", "E eu levo mais fita. Muito mais."),
    ]},

    "e1_epilogo": {"bg": "garagem", "cast": ["teo", "ambrosio", "vivi", "bia", "dudu", "gervasio", "ze"], "lines": [
        ("narrador", "neutro", "Duas semanas depois. Garagem do Vô Nestor. Cheiro de graxa, naftalina e, desta vez, de pão de queijo de hoje."),
        ("gervasio", "feliz", "Moreira! Boas notícias. O clube de robótica não fecha. O conselho pediu desculpas. Eu também. Menos o refeitório."),
        ("teo", "feliz", "Diretor Gervásio, o senhor está chorando?"),
        ("bia", "feliz", "Eu pendurei o troféu no teto, com fita. Se cair, a gente chama de arte."),
        ("vivi", "corada", "Eu, oficialmente, abandonei a presidência do Grêmio para virar capitã do time. Falei com meus pais. Eles pediram planilha."),
        ("dudu", "feliz", "Chat, a live de hoje é a mais longa da história: trinta e seis horas. Minha mãe trouxe uma cadeira."),
        ("narrador", "neutro", "O telefone fixo toca. Do outro lado, um barulho de mar, bufê e um violão desafinado. É o Vô Nestor, ligando de um cruzeiro."),
        ("narrador", "neutro", "No viva-voz, o Vô Nestor: \"Alô? Téo? Vi o Mundial no telão do navio! Os outros hóspedes acharam que era filme. Um senhor chorou.\""),
        ("teo", "feliz", "Vô! A gente ganhou! E o Zé Poeira estava com o seu chip original!"),
        ("narrador", "neutro", "Vô Nestor, rindo: \"Eu sei, filho. Escondi o chip no Zé de propósito. Quem tem um chinelo e um chip honesto não precisa de overclock.\""),
        ("ambrosio", "feliz", "Nestor, seu velho gambiarreiro. Você planejou isso por trinta anos?"),
        ("narrador", "neutro", "Vô Nestor: \"Cochilei em vinte e nove. Mas deu certo. Agora desligo, que vai começar o bingo.\" Clique. Bingo."),
        ("narrador", "neutro", "Créditos: Téo, Prof. Ambrósio, Vivi, Bia, Dudu, Vô Nestor e o chinelo (estrutural). Nenhuma poeira foi ferida durante a produção."),
        ("ze", "robo", "Bzzzt. (a rodinha esquerda cai e rola até a porta. Fim. Pode pegar a rodinha.)"),
    ]},
}

# --- recompensas (aplicadas uma vez ao fechar o capitulo; idempotentes pela lista `done`) -------
REWARDS = {
    "rw_P": {"scrap": 30, "piece": None, "recruits": [], "unlock": [], "xp_hero": 40, "xp_team": 0,
             "equip_hero_piece": None},
    "rw_1": {"scrap": 120, "piece": {"model": "Escova de Sucção", "rar": 1},
             "recruits": [{"name": "Gambiarra", "role": "DEF", "chassis": "Tanque", "base_ovr": 50,
                           "level": 3, "paint": (255, 150, 40),
                           "piece": {"model": "Borracha", "rar": 0}}],
             "unlock": ["Tanque"], "xp_hero": 30, "xp_team": 0, "equip_hero_piece": None},
    "rw_2": {"scrap": 150, "piece": {"model": "Chip de CPU", "rar": 2},
             "recruits": [{"name": "Pixelado", "role": "MID", "chassis": "Orbital", "base_ovr": 54,
                           "level": 4, "paint": (60, 220, 130),
                           "piece": {"model": "Célula Rápida", "rar": 0}}],
             "unlock": ["Velocista"], "xp_hero": 30, "xp_team": 0, "equip_hero_piece": None},
    "rw_3": {"scrap": 300, "piece": None, "recruits": [], "unlock": ["Goleiro"], "xp_hero": 40,
             "xp_team": 0, "equip_hero_piece": None},
    # Cap. 4: peca Epica, Valentina + "Majestade" (Titã) e a LENDARIA "Chip do Vovo" equipada no heroi
    "rw_4": {"scrap": 300, "piece": {"model": "Vácuo Turbo", "rar": 2},
             "recruits": [{"name": "Majestade", "role": "DEF", "chassis": "Titã", "base_ovr": 64,
                           "level": 5, "paint": (30, 60, 130),
                           "piece": {"model": "Blindado", "rar": 1}}],
             "unlock": ["Titã"], "xp_hero": 0, "xp_team": 0,
             "equip_hero_piece": {"model": "Chip de CPU", "rar": 3}},
    # Cap. 5: titulo mundial (stats.titles) e fim da campanha
    "rw_5": {"scrap": 600, "piece": None, "recruits": [], "unlock": [], "xp_hero": 0, "xp_team": 0,
             "equip_hero_piece": None, "title": True},
}

# --- capitulos ----------------------------------------------------------------------------------
# F_start/F_end = Forca esperada do jogador "normal" (tabela do plano). econ_tier = tier passado a
# garage.match_rewards/refresh_shop durante o capitulo (= tier_done + 1 do Garage). tier_done_on_close
# = clamp(cap-1, -1, 3) gravado em garage.tier_done ao fechar.
CHAPTERS = [
    {"id": "P", "title": "Prólogo", "subtitle": "A Garagem do Vô", "local": "Garagem e Colégio Santa Faísca",
     "F_start": 44.3, "F_end": 44.3, "econ_tier": 0, "tier_done_on_close": -1, "reward": "rw_P",
     "nodes": [("scene", "p1_garagem"), ("scene", "p2_oficina"), ("scene", "p3_peneira_pre"),
               ("tournament", "t_p_treino"), ("scene", "p4_peneira_pos"), ("chapter_end", "P")]},
    {"id": "1", "title": "Capítulo 1", "subtitle": "Copa Interclasses", "local": "Colégio Santa Faísca",
     "F_start": 44.6, "F_end": 47.0, "econ_tier": 0, "tier_done_on_close": 0, "reward": "rw_1",
     "nodes": [("scene", "c1_intro"), ("tournament", "t_c1"), ("scene", "c1_end"),
               ("chapter_end", "1")]},
    {"id": "2", "title": "Capítulo 2", "subtitle": "Taça Vale do Pó", "local": "Ginásio Municipal",
     "F_start": 49.7, "F_end": 51.2, "econ_tier": 1, "tier_done_on_close": 1, "reward": "rw_2",
     "nodes": [("scene", "c2_intro"), ("tournament", "t_c2"), ("scene", "c2_end"),
               ("chapter_end", "2")]},
    {"id": "3", "title": "Capítulo 3", "subtitle": "Estadual Limpex Cup", "local": "Arena Estadual",
     "F_start": 53.5, "F_end": 55.0, "econ_tier": 2, "tier_done_on_close": 2, "reward": "rw_3",
     "nodes": [("scene", "c3_intro"), ("tournament", "t_c3"), ("scene", "c3_end"),
               ("chapter_end", "3")]},
    {"id": "4", "title": "Capítulo 4", "subtitle": "Copa Brasil", "local": "Estádio Nacional",
     "F_start": 55.8, "F_end": 57.2, "econ_tier": 3, "tier_done_on_close": 3, "reward": "rw_4",
     "nodes": [("scene", "c4_intro"), ("tournament", "t_c4"), ("scene", "c4_end"),
               ("chapter_end", "4")]},
    {"id": "5", "title": "Capítulo 5", "subtitle": "Mundial de Aspiradores", "local": "Arena Global de Neo-Tóquio",
     "F_start": 61.2, "F_end": 62.5, "econ_tier": 3, "tier_done_on_close": 3, "reward": "rw_5",
     "nodes": [("scene", "c5_intro"), ("tournament", "t_c5"), ("scene", "c5_antidoping"),
               ("chapter_end", "5"), ("end", "e1_epilogo")]},
]
